// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/ygpark2/njro/service/comment/ent/comment"
)

// CommentCreate is the builder for creating a Comment entity.
type CommentCreate struct {
	config
	mutation *CommentMutation
	hooks    []Hook
}

// SetBoardID sets the "board_id" field.
func (cc *CommentCreate) SetBoardID(s string) *CommentCreate {
	cc.mutation.SetBoardID(s)
	return cc
}

// SetPostID sets the "post_id" field.
func (cc *CommentCreate) SetPostID(s string) *CommentCreate {
	cc.mutation.SetPostID(s)
	return cc
}

// SetContentID sets the "content_id" field.
func (cc *CommentCreate) SetContentID(s string) *CommentCreate {
	cc.mutation.SetContentID(s)
	return cc
}

// SetNillableContentID sets the "content_id" field if the given value is not nil.
func (cc *CommentCreate) SetNillableContentID(s *string) *CommentCreate {
	if s != nil {
		cc.SetContentID(*s)
	}
	return cc
}

// SetUserid sets the "userid" field.
func (cc *CommentCreate) SetUserid(s string) *CommentCreate {
	cc.mutation.SetUserid(s)
	return cc
}

// SetUsername sets the "username" field.
func (cc *CommentCreate) SetUsername(s string) *CommentCreate {
	cc.mutation.SetUsername(s)
	return cc
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (cc *CommentCreate) SetNillableUsername(s *string) *CommentCreate {
	if s != nil {
		cc.SetUsername(*s)
	}
	return cc
}

// SetNickname sets the "nickname" field.
func (cc *CommentCreate) SetNickname(s string) *CommentCreate {
	cc.mutation.SetNickname(s)
	return cc
}

// SetNillableNickname sets the "nickname" field if the given value is not nil.
func (cc *CommentCreate) SetNillableNickname(s *string) *CommentCreate {
	if s != nil {
		cc.SetNickname(*s)
	}
	return cc
}

// SetEmail sets the "email" field.
func (cc *CommentCreate) SetEmail(s string) *CommentCreate {
	cc.mutation.SetEmail(s)
	return cc
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (cc *CommentCreate) SetNillableEmail(s *string) *CommentCreate {
	if s != nil {
		cc.SetEmail(*s)
	}
	return cc
}

// SetPassword sets the "password" field.
func (cc *CommentCreate) SetPassword(s string) *CommentCreate {
	cc.mutation.SetPassword(s)
	return cc
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (cc *CommentCreate) SetNillablePassword(s *string) *CommentCreate {
	if s != nil {
		cc.SetPassword(*s)
	}
	return cc
}

// SetContent sets the "content" field.
func (cc *CommentCreate) SetContent(s string) *CommentCreate {
	cc.mutation.SetContent(s)
	return cc
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (cc *CommentCreate) SetNillableContent(s *string) *CommentCreate {
	if s != nil {
		cc.SetContent(*s)
	}
	return cc
}

// SetURL sets the "url" field.
func (cc *CommentCreate) SetURL(s string) *CommentCreate {
	cc.mutation.SetURL(s)
	return cc
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (cc *CommentCreate) SetNillableURL(s *string) *CommentCreate {
	if s != nil {
		cc.SetURL(*s)
	}
	return cc
}

// SetUseHTML sets the "use_html" field.
func (cc *CommentCreate) SetUseHTML(b bool) *CommentCreate {
	cc.mutation.SetUseHTML(b)
	return cc
}

// SetNillableUseHTML sets the "use_html" field if the given value is not nil.
func (cc *CommentCreate) SetNillableUseHTML(b *bool) *CommentCreate {
	if b != nil {
		cc.SetUseHTML(*b)
	}
	return cc
}

// SetUseSecret sets the "use_secret" field.
func (cc *CommentCreate) SetUseSecret(b bool) *CommentCreate {
	cc.mutation.SetUseSecret(b)
	return cc
}

// SetNillableUseSecret sets the "use_secret" field if the given value is not nil.
func (cc *CommentCreate) SetNillableUseSecret(b *bool) *CommentCreate {
	if b != nil {
		cc.SetUseSecret(*b)
	}
	return cc
}

// SetUpVoteCount sets the "up_vote_count" field.
func (cc *CommentCreate) SetUpVoteCount(u uint32) *CommentCreate {
	cc.mutation.SetUpVoteCount(u)
	return cc
}

// SetNillableUpVoteCount sets the "up_vote_count" field if the given value is not nil.
func (cc *CommentCreate) SetNillableUpVoteCount(u *uint32) *CommentCreate {
	if u != nil {
		cc.SetUpVoteCount(*u)
	}
	return cc
}

// SetDownVoteCount sets the "down_vote_count" field.
func (cc *CommentCreate) SetDownVoteCount(u uint32) *CommentCreate {
	cc.mutation.SetDownVoteCount(u)
	return cc
}

// SetNillableDownVoteCount sets the "down_vote_count" field if the given value is not nil.
func (cc *CommentCreate) SetNillableDownVoteCount(u *uint32) *CommentCreate {
	if u != nil {
		cc.SetDownVoteCount(*u)
	}
	return cc
}

// SetCreatedAt sets the "created_at" field.
func (cc *CommentCreate) SetCreatedAt(t time.Time) *CommentCreate {
	cc.mutation.SetCreatedAt(t)
	return cc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cc *CommentCreate) SetNillableCreatedAt(t *time.Time) *CommentCreate {
	if t != nil {
		cc.SetCreatedAt(*t)
	}
	return cc
}

// SetUpdatedAt sets the "updated_at" field.
func (cc *CommentCreate) SetUpdatedAt(t time.Time) *CommentCreate {
	cc.mutation.SetUpdatedAt(t)
	return cc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (cc *CommentCreate) SetNillableUpdatedAt(t *time.Time) *CommentCreate {
	if t != nil {
		cc.SetUpdatedAt(*t)
	}
	return cc
}

// SetID sets the "id" field.
func (cc *CommentCreate) SetID(u uuid.UUID) *CommentCreate {
	cc.mutation.SetID(u)
	return cc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (cc *CommentCreate) SetNillableID(u *uuid.UUID) *CommentCreate {
	if u != nil {
		cc.SetID(*u)
	}
	return cc
}

// Mutation returns the CommentMutation object of the builder.
func (cc *CommentCreate) Mutation() *CommentMutation {
	return cc.mutation
}

// Save creates the Comment in the database.
func (cc *CommentCreate) Save(ctx context.Context) (*Comment, error) {
	cc.defaults()
	return withHooks(ctx, cc.sqlSave, cc.mutation, cc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (cc *CommentCreate) SaveX(ctx context.Context) *Comment {
	v, err := cc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cc *CommentCreate) Exec(ctx context.Context) error {
	_, err := cc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cc *CommentCreate) ExecX(ctx context.Context) {
	if err := cc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cc *CommentCreate) defaults() {
	if _, ok := cc.mutation.ContentID(); !ok {
		v := comment.DefaultContentID
		cc.mutation.SetContentID(v)
	}
	if _, ok := cc.mutation.Username(); !ok {
		v := comment.DefaultUsername
		cc.mutation.SetUsername(v)
	}
	if _, ok := cc.mutation.Nickname(); !ok {
		v := comment.DefaultNickname
		cc.mutation.SetNickname(v)
	}
	if _, ok := cc.mutation.Email(); !ok {
		v := comment.DefaultEmail
		cc.mutation.SetEmail(v)
	}
	if _, ok := cc.mutation.Password(); !ok {
		v := comment.DefaultPassword
		cc.mutation.SetPassword(v)
	}
	if _, ok := cc.mutation.Content(); !ok {
		v := comment.DefaultContent
		cc.mutation.SetContent(v)
	}
	if _, ok := cc.mutation.URL(); !ok {
		v := comment.DefaultURL
		cc.mutation.SetURL(v)
	}
	if _, ok := cc.mutation.UseHTML(); !ok {
		v := comment.DefaultUseHTML
		cc.mutation.SetUseHTML(v)
	}
	if _, ok := cc.mutation.UseSecret(); !ok {
		v := comment.DefaultUseSecret
		cc.mutation.SetUseSecret(v)
	}
	if _, ok := cc.mutation.UpVoteCount(); !ok {
		v := comment.DefaultUpVoteCount
		cc.mutation.SetUpVoteCount(v)
	}
	if _, ok := cc.mutation.DownVoteCount(); !ok {
		v := comment.DefaultDownVoteCount
		cc.mutation.SetDownVoteCount(v)
	}
	if _, ok := cc.mutation.CreatedAt(); !ok {
		v := comment.DefaultCreatedAt()
		cc.mutation.SetCreatedAt(v)
	}
	if _, ok := cc.mutation.UpdatedAt(); !ok {
		v := comment.DefaultUpdatedAt()
		cc.mutation.SetUpdatedAt(v)
	}
	if _, ok := cc.mutation.ID(); !ok {
		v := comment.DefaultID()
		cc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cc *CommentCreate) check() error {
	if _, ok := cc.mutation.BoardID(); !ok {
		return &ValidationError{Name: "board_id", err: errors.New(`ent: missing required field "Comment.board_id"`)}
	}
	if v, ok := cc.mutation.BoardID(); ok {
		if err := comment.BoardIDValidator(v); err != nil {
			return &ValidationError{Name: "board_id", err: fmt.Errorf(`ent: validator failed for field "Comment.board_id": %w`, err)}
		}
	}
	if _, ok := cc.mutation.PostID(); !ok {
		return &ValidationError{Name: "post_id", err: errors.New(`ent: missing required field "Comment.post_id"`)}
	}
	if v, ok := cc.mutation.PostID(); ok {
		if err := comment.PostIDValidator(v); err != nil {
			return &ValidationError{Name: "post_id", err: fmt.Errorf(`ent: validator failed for field "Comment.post_id": %w`, err)}
		}
	}
	if _, ok := cc.mutation.ContentID(); !ok {
		return &ValidationError{Name: "content_id", err: errors.New(`ent: missing required field "Comment.content_id"`)}
	}
	if _, ok := cc.mutation.Userid(); !ok {
		return &ValidationError{Name: "userid", err: errors.New(`ent: missing required field "Comment.userid"`)}
	}
	if v, ok := cc.mutation.Userid(); ok {
		if err := comment.UseridValidator(v); err != nil {
			return &ValidationError{Name: "userid", err: fmt.Errorf(`ent: validator failed for field "Comment.userid": %w`, err)}
		}
	}
	if _, ok := cc.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New(`ent: missing required field "Comment.username"`)}
	}
	if _, ok := cc.mutation.Nickname(); !ok {
		return &ValidationError{Name: "nickname", err: errors.New(`ent: missing required field "Comment.nickname"`)}
	}
	if _, ok := cc.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "Comment.email"`)}
	}
	if _, ok := cc.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "Comment.content"`)}
	}
	if _, ok := cc.mutation.UseHTML(); !ok {
		return &ValidationError{Name: "use_html", err: errors.New(`ent: missing required field "Comment.use_html"`)}
	}
	if _, ok := cc.mutation.UseSecret(); !ok {
		return &ValidationError{Name: "use_secret", err: errors.New(`ent: missing required field "Comment.use_secret"`)}
	}
	if _, ok := cc.mutation.UpVoteCount(); !ok {
		return &ValidationError{Name: "up_vote_count", err: errors.New(`ent: missing required field "Comment.up_vote_count"`)}
	}
	if _, ok := cc.mutation.DownVoteCount(); !ok {
		return &ValidationError{Name: "down_vote_count", err: errors.New(`ent: missing required field "Comment.down_vote_count"`)}
	}
	if _, ok := cc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Comment.created_at"`)}
	}
	if _, ok := cc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Comment.updated_at"`)}
	}
	return nil
}

func (cc *CommentCreate) sqlSave(ctx context.Context) (*Comment, error) {
	if err := cc.check(); err != nil {
		return nil, err
	}
	_node, _spec := cc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	cc.mutation.id = &_node.ID
	cc.mutation.done = true
	return _node, nil
}

func (cc *CommentCreate) createSpec() (*Comment, *sqlgraph.CreateSpec) {
	var (
		_node = &Comment{config: cc.config}
		_spec = sqlgraph.NewCreateSpec(comment.Table, sqlgraph.NewFieldSpec(comment.FieldID, field.TypeUUID))
	)
	if id, ok := cc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := cc.mutation.BoardID(); ok {
		_spec.SetField(comment.FieldBoardID, field.TypeString, value)
		_node.BoardID = value
	}
	if value, ok := cc.mutation.PostID(); ok {
		_spec.SetField(comment.FieldPostID, field.TypeString, value)
		_node.PostID = value
	}
	if value, ok := cc.mutation.ContentID(); ok {
		_spec.SetField(comment.FieldContentID, field.TypeString, value)
		_node.ContentID = value
	}
	if value, ok := cc.mutation.Userid(); ok {
		_spec.SetField(comment.FieldUserid, field.TypeString, value)
		_node.Userid = value
	}
	if value, ok := cc.mutation.Username(); ok {
		_spec.SetField(comment.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := cc.mutation.Nickname(); ok {
		_spec.SetField(comment.FieldNickname, field.TypeString, value)
		_node.Nickname = value
	}
	if value, ok := cc.mutation.Email(); ok {
		_spec.SetField(comment.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := cc.mutation.Password(); ok {
		_spec.SetField(comment.FieldPassword, field.TypeString, value)
		_node.Password = value
	}
	if value, ok := cc.mutation.Content(); ok {
		_spec.SetField(comment.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := cc.mutation.URL(); ok {
		_spec.SetField(comment.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := cc.mutation.UseHTML(); ok {
		_spec.SetField(comment.FieldUseHTML, field.TypeBool, value)
		_node.UseHTML = value
	}
	if value, ok := cc.mutation.UseSecret(); ok {
		_spec.SetField(comment.FieldUseSecret, field.TypeBool, value)
		_node.UseSecret = value
	}
	if value, ok := cc.mutation.UpVoteCount(); ok {
		_spec.SetField(comment.FieldUpVoteCount, field.TypeUint32, value)
		_node.UpVoteCount = value
	}
	if value, ok := cc.mutation.DownVoteCount(); ok {
		_spec.SetField(comment.FieldDownVoteCount, field.TypeUint32, value)
		_node.DownVoteCount = value
	}
	if value, ok := cc.mutation.CreatedAt(); ok {
		_spec.SetField(comment.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := cc.mutation.UpdatedAt(); ok {
		_spec.SetField(comment.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// CommentCreateBulk is the builder for creating many Comment entities in bulk.
type CommentCreateBulk struct {
	config
	err      error
	builders []*CommentCreate
}

// Save creates the Comment entities in the database.
func (ccb *CommentCreateBulk) Save(ctx context.Context) ([]*Comment, error) {
	if ccb.err != nil {
		return nil, ccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ccb.builders))
	nodes := make([]*Comment, len(ccb.builders))
	mutators := make([]Mutator, len(ccb.builders))
	for i := range ccb.builders {
		func(i int, root context.Context) {
			builder := ccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CommentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ccb *CommentCreateBulk) SaveX(ctx context.Context) []*Comment {
	v, err := ccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ccb *CommentCreateBulk) Exec(ctx context.Context) error {
	_, err := ccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ccb *CommentCreateBulk) ExecX(ctx context.Context) {
	if err := ccb.Exec(ctx); err != nil {
		panic(err)
	}
}
