// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ygpark2/njro/service/comment/ent/comment"
	"github.com/ygpark2/njro/service/comment/ent/predicate"
)

// CommentUpdate is the builder for updating Comment entities.
type CommentUpdate struct {
	config
	hooks    []Hook
	mutation *CommentMutation
}

// Where appends a list predicates to the CommentUpdate builder.
func (cu *CommentUpdate) Where(ps ...predicate.Comment) *CommentUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetContentID sets the "content_id" field.
func (cu *CommentUpdate) SetContentID(s string) *CommentUpdate {
	cu.mutation.SetContentID(s)
	return cu
}

// SetNillableContentID sets the "content_id" field if the given value is not nil.
func (cu *CommentUpdate) SetNillableContentID(s *string) *CommentUpdate {
	if s != nil {
		cu.SetContentID(*s)
	}
	return cu
}

// SetUsername sets the "username" field.
func (cu *CommentUpdate) SetUsername(s string) *CommentUpdate {
	cu.mutation.SetUsername(s)
	return cu
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (cu *CommentUpdate) SetNillableUsername(s *string) *CommentUpdate {
	if s != nil {
		cu.SetUsername(*s)
	}
	return cu
}

// SetNickname sets the "nickname" field.
func (cu *CommentUpdate) SetNickname(s string) *CommentUpdate {
	cu.mutation.SetNickname(s)
	return cu
}

// SetNillableNickname sets the "nickname" field if the given value is not nil.
func (cu *CommentUpdate) SetNillableNickname(s *string) *CommentUpdate {
	if s != nil {
		cu.SetNickname(*s)
	}
	return cu
}

// SetEmail sets the "email" field.
func (cu *CommentUpdate) SetEmail(s string) *CommentUpdate {
	cu.mutation.SetEmail(s)
	return cu
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (cu *CommentUpdate) SetNillableEmail(s *string) *CommentUpdate {
	if s != nil {
		cu.SetEmail(*s)
	}
	return cu
}

// SetPassword sets the "password" field.
func (cu *CommentUpdate) SetPassword(s string) *CommentUpdate {
	cu.mutation.SetPassword(s)
	return cu
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (cu *CommentUpdate) SetNillablePassword(s *string) *CommentUpdate {
	if s != nil {
		cu.SetPassword(*s)
	}
	return cu
}

// ClearPassword clears the value of the "password" field.
func (cu *CommentUpdate) ClearPassword() *CommentUpdate {
	cu.mutation.ClearPassword()
	return cu
}

// SetContent sets the "content" field.
func (cu *CommentUpdate) SetContent(s string) *CommentUpdate {
	cu.mutation.SetContent(s)
	return cu
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (cu *CommentUpdate) SetNillableContent(s *string) *CommentUpdate {
	if s != nil {
		cu.SetContent(*s)
	}
	return cu
}

// SetURL sets the "url" field.
func (cu *CommentUpdate) SetURL(s string) *CommentUpdate {
	cu.mutation.SetURL(s)
	return cu
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (cu *CommentUpdate) SetNillableURL(s *string) *CommentUpdate {
	if s != nil {
		cu.SetURL(*s)
	}
	return cu
}

// ClearURL clears the value of the "url" field.
func (cu *CommentUpdate) ClearURL() *CommentUpdate {
	cu.mutation.ClearURL()
	return cu
}

// SetUseHTML sets the "use_html" field.
func (cu *CommentUpdate) SetUseHTML(b bool) *CommentUpdate {
	cu.mutation.SetUseHTML(b)
	return cu
}

// SetNillableUseHTML sets the "use_html" field if the given value is not nil.
func (cu *CommentUpdate) SetNillableUseHTML(b *bool) *CommentUpdate {
	if b != nil {
		cu.SetUseHTML(*b)
	}
	return cu
}

// SetUseSecret sets the "use_secret" field.
func (cu *CommentUpdate) SetUseSecret(b bool) *CommentUpdate {
	cu.mutation.SetUseSecret(b)
	return cu
}

// SetNillableUseSecret sets the "use_secret" field if the given value is not nil.
func (cu *CommentUpdate) SetNillableUseSecret(b *bool) *CommentUpdate {
	if b != nil {
		cu.SetUseSecret(*b)
	}
	return cu
}

// SetUpVoteCount sets the "up_vote_count" field.
func (cu *CommentUpdate) SetUpVoteCount(u uint32) *CommentUpdate {
	cu.mutation.ResetUpVoteCount()
	cu.mutation.SetUpVoteCount(u)
	return cu
}

// SetNillableUpVoteCount sets the "up_vote_count" field if the given value is not nil.
func (cu *CommentUpdate) SetNillableUpVoteCount(u *uint32) *CommentUpdate {
	if u != nil {
		cu.SetUpVoteCount(*u)
	}
	return cu
}

// AddUpVoteCount adds u to the "up_vote_count" field.
func (cu *CommentUpdate) AddUpVoteCount(u int32) *CommentUpdate {
	cu.mutation.AddUpVoteCount(u)
	return cu
}

// SetDownVoteCount sets the "down_vote_count" field.
func (cu *CommentUpdate) SetDownVoteCount(u uint32) *CommentUpdate {
	cu.mutation.ResetDownVoteCount()
	cu.mutation.SetDownVoteCount(u)
	return cu
}

// SetNillableDownVoteCount sets the "down_vote_count" field if the given value is not nil.
func (cu *CommentUpdate) SetNillableDownVoteCount(u *uint32) *CommentUpdate {
	if u != nil {
		cu.SetDownVoteCount(*u)
	}
	return cu
}

// AddDownVoteCount adds u to the "down_vote_count" field.
func (cu *CommentUpdate) AddDownVoteCount(u int32) *CommentUpdate {
	cu.mutation.AddDownVoteCount(u)
	return cu
}

// SetUpdatedAt sets the "updated_at" field.
func (cu *CommentUpdate) SetUpdatedAt(t time.Time) *CommentUpdate {
	cu.mutation.SetUpdatedAt(t)
	return cu
}

// Mutation returns the CommentMutation object of the builder.
func (cu *CommentUpdate) Mutation() *CommentMutation {
	return cu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *CommentUpdate) Save(ctx context.Context) (int, error) {
	cu.defaults()
	return withHooks(ctx, cu.sqlSave, cu.mutation, cu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cu *CommentUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *CommentUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *CommentUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cu *CommentUpdate) defaults() {
	if _, ok := cu.mutation.UpdatedAt(); !ok {
		v := comment.UpdateDefaultUpdatedAt()
		cu.mutation.SetUpdatedAt(v)
	}
}

func (cu *CommentUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(comment.Table, comment.Columns, sqlgraph.NewFieldSpec(comment.FieldID, field.TypeUUID))
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.ContentID(); ok {
		_spec.SetField(comment.FieldContentID, field.TypeString, value)
	}
	if value, ok := cu.mutation.Username(); ok {
		_spec.SetField(comment.FieldUsername, field.TypeString, value)
	}
	if value, ok := cu.mutation.Nickname(); ok {
		_spec.SetField(comment.FieldNickname, field.TypeString, value)
	}
	if value, ok := cu.mutation.Email(); ok {
		_spec.SetField(comment.FieldEmail, field.TypeString, value)
	}
	if value, ok := cu.mutation.Password(); ok {
		_spec.SetField(comment.FieldPassword, field.TypeString, value)
	}
	if cu.mutation.PasswordCleared() {
		_spec.ClearField(comment.FieldPassword, field.TypeString)
	}
	if value, ok := cu.mutation.Content(); ok {
		_spec.SetField(comment.FieldContent, field.TypeString, value)
	}
	if value, ok := cu.mutation.URL(); ok {
		_spec.SetField(comment.FieldURL, field.TypeString, value)
	}
	if cu.mutation.URLCleared() {
		_spec.ClearField(comment.FieldURL, field.TypeString)
	}
	if value, ok := cu.mutation.UseHTML(); ok {
		_spec.SetField(comment.FieldUseHTML, field.TypeBool, value)
	}
	if value, ok := cu.mutation.UseSecret(); ok {
		_spec.SetField(comment.FieldUseSecret, field.TypeBool, value)
	}
	if value, ok := cu.mutation.UpVoteCount(); ok {
		_spec.SetField(comment.FieldUpVoteCount, field.TypeUint32, value)
	}
	if value, ok := cu.mutation.AddedUpVoteCount(); ok {
		_spec.AddField(comment.FieldUpVoteCount, field.TypeUint32, value)
	}
	if value, ok := cu.mutation.DownVoteCount(); ok {
		_spec.SetField(comment.FieldDownVoteCount, field.TypeUint32, value)
	}
	if value, ok := cu.mutation.AddedDownVoteCount(); ok {
		_spec.AddField(comment.FieldDownVoteCount, field.TypeUint32, value)
	}
	if value, ok := cu.mutation.UpdatedAt(); ok {
		_spec.SetField(comment.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{comment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cu.mutation.done = true
	return n, nil
}

// CommentUpdateOne is the builder for updating a single Comment entity.
type CommentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CommentMutation
}

// SetContentID sets the "content_id" field.
func (cuo *CommentUpdateOne) SetContentID(s string) *CommentUpdateOne {
	cuo.mutation.SetContentID(s)
	return cuo
}

// SetNillableContentID sets the "content_id" field if the given value is not nil.
func (cuo *CommentUpdateOne) SetNillableContentID(s *string) *CommentUpdateOne {
	if s != nil {
		cuo.SetContentID(*s)
	}
	return cuo
}

// SetUsername sets the "username" field.
func (cuo *CommentUpdateOne) SetUsername(s string) *CommentUpdateOne {
	cuo.mutation.SetUsername(s)
	return cuo
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (cuo *CommentUpdateOne) SetNillableUsername(s *string) *CommentUpdateOne {
	if s != nil {
		cuo.SetUsername(*s)
	}
	return cuo
}

// SetNickname sets the "nickname" field.
func (cuo *CommentUpdateOne) SetNickname(s string) *CommentUpdateOne {
	cuo.mutation.SetNickname(s)
	return cuo
}

// SetNillableNickname sets the "nickname" field if the given value is not nil.
func (cuo *CommentUpdateOne) SetNillableNickname(s *string) *CommentUpdateOne {
	if s != nil {
		cuo.SetNickname(*s)
	}
	return cuo
}

// SetEmail sets the "email" field.
func (cuo *CommentUpdateOne) SetEmail(s string) *CommentUpdateOne {
	cuo.mutation.SetEmail(s)
	return cuo
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (cuo *CommentUpdateOne) SetNillableEmail(s *string) *CommentUpdateOne {
	if s != nil {
		cuo.SetEmail(*s)
	}
	return cuo
}

// SetPassword sets the "password" field.
func (cuo *CommentUpdateOne) SetPassword(s string) *CommentUpdateOne {
	cuo.mutation.SetPassword(s)
	return cuo
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (cuo *CommentUpdateOne) SetNillablePassword(s *string) *CommentUpdateOne {
	if s != nil {
		cuo.SetPassword(*s)
	}
	return cuo
}

// ClearPassword clears the value of the "password" field.
func (cuo *CommentUpdateOne) ClearPassword() *CommentUpdateOne {
	cuo.mutation.ClearPassword()
	return cuo
}

// SetContent sets the "content" field.
func (cuo *CommentUpdateOne) SetContent(s string) *CommentUpdateOne {
	cuo.mutation.SetContent(s)
	return cuo
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (cuo *CommentUpdateOne) SetNillableContent(s *string) *CommentUpdateOne {
	if s != nil {
		cuo.SetContent(*s)
	}
	return cuo
}

// SetURL sets the "url" field.
func (cuo *CommentUpdateOne) SetURL(s string) *CommentUpdateOne {
	cuo.mutation.SetURL(s)
	return cuo
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (cuo *CommentUpdateOne) SetNillableURL(s *string) *CommentUpdateOne {
	if s != nil {
		cuo.SetURL(*s)
	}
	return cuo
}

// ClearURL clears the value of the "url" field.
func (cuo *CommentUpdateOne) ClearURL() *CommentUpdateOne {
	cuo.mutation.ClearURL()
	return cuo
}

// SetUseHTML sets the "use_html" field.
func (cuo *CommentUpdateOne) SetUseHTML(b bool) *CommentUpdateOne {
	cuo.mutation.SetUseHTML(b)
	return cuo
}

// SetNillableUseHTML sets the "use_html" field if the given value is not nil.
func (cuo *CommentUpdateOne) SetNillableUseHTML(b *bool) *CommentUpdateOne {
	if b != nil {
		cuo.SetUseHTML(*b)
	}
	return cuo
}

// SetUseSecret sets the "use_secret" field.
func (cuo *CommentUpdateOne) SetUseSecret(b bool) *CommentUpdateOne {
	cuo.mutation.SetUseSecret(b)
	return cuo
}

// SetNillableUseSecret sets the "use_secret" field if the given value is not nil.
func (cuo *CommentUpdateOne) SetNillableUseSecret(b *bool) *CommentUpdateOne {
	if b != nil {
		cuo.SetUseSecret(*b)
	}
	return cuo
}

// SetUpVoteCount sets the "up_vote_count" field.
func (cuo *CommentUpdateOne) SetUpVoteCount(u uint32) *CommentUpdateOne {
	cuo.mutation.ResetUpVoteCount()
	cuo.mutation.SetUpVoteCount(u)
	return cuo
}

// SetNillableUpVoteCount sets the "up_vote_count" field if the given value is not nil.
func (cuo *CommentUpdateOne) SetNillableUpVoteCount(u *uint32) *CommentUpdateOne {
	if u != nil {
		cuo.SetUpVoteCount(*u)
	}
	return cuo
}

// AddUpVoteCount adds u to the "up_vote_count" field.
func (cuo *CommentUpdateOne) AddUpVoteCount(u int32) *CommentUpdateOne {
	cuo.mutation.AddUpVoteCount(u)
	return cuo
}

// SetDownVoteCount sets the "down_vote_count" field.
func (cuo *CommentUpdateOne) SetDownVoteCount(u uint32) *CommentUpdateOne {
	cuo.mutation.ResetDownVoteCount()
	cuo.mutation.SetDownVoteCount(u)
	return cuo
}

// SetNillableDownVoteCount sets the "down_vote_count" field if the given value is not nil.
func (cuo *CommentUpdateOne) SetNillableDownVoteCount(u *uint32) *CommentUpdateOne {
	if u != nil {
		cuo.SetDownVoteCount(*u)
	}
	return cuo
}

// AddDownVoteCount adds u to the "down_vote_count" field.
func (cuo *CommentUpdateOne) AddDownVoteCount(u int32) *CommentUpdateOne {
	cuo.mutation.AddDownVoteCount(u)
	return cuo
}

// SetUpdatedAt sets the "updated_at" field.
func (cuo *CommentUpdateOne) SetUpdatedAt(t time.Time) *CommentUpdateOne {
	cuo.mutation.SetUpdatedAt(t)
	return cuo
}

// Mutation returns the CommentMutation object of the builder.
func (cuo *CommentUpdateOne) Mutation() *CommentMutation {
	return cuo.mutation
}

// Where appends a list predicates to the CommentUpdate builder.
func (cuo *CommentUpdateOne) Where(ps ...predicate.Comment) *CommentUpdateOne {
	cuo.mutation.Where(ps...)
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *CommentUpdateOne) Select(field string, fields ...string) *CommentUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Comment entity.
func (cuo *CommentUpdateOne) Save(ctx context.Context) (*Comment, error) {
	cuo.defaults()
	return withHooks(ctx, cuo.sqlSave, cuo.mutation, cuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *CommentUpdateOne) SaveX(ctx context.Context) *Comment {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *CommentUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *CommentUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cuo *CommentUpdateOne) defaults() {
	if _, ok := cuo.mutation.UpdatedAt(); !ok {
		v := comment.UpdateDefaultUpdatedAt()
		cuo.mutation.SetUpdatedAt(v)
	}
}

func (cuo *CommentUpdateOne) sqlSave(ctx context.Context) (_node *Comment, err error) {
	_spec := sqlgraph.NewUpdateSpec(comment.Table, comment.Columns, sqlgraph.NewFieldSpec(comment.FieldID, field.TypeUUID))
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Comment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, comment.FieldID)
		for _, f := range fields {
			if !comment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != comment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.ContentID(); ok {
		_spec.SetField(comment.FieldContentID, field.TypeString, value)
	}
	if value, ok := cuo.mutation.Username(); ok {
		_spec.SetField(comment.FieldUsername, field.TypeString, value)
	}
	if value, ok := cuo.mutation.Nickname(); ok {
		_spec.SetField(comment.FieldNickname, field.TypeString, value)
	}
	if value, ok := cuo.mutation.Email(); ok {
		_spec.SetField(comment.FieldEmail, field.TypeString, value)
	}
	if value, ok := cuo.mutation.Password(); ok {
		_spec.SetField(comment.FieldPassword, field.TypeString, value)
	}
	if cuo.mutation.PasswordCleared() {
		_spec.ClearField(comment.FieldPassword, field.TypeString)
	}
	if value, ok := cuo.mutation.Content(); ok {
		_spec.SetField(comment.FieldContent, field.TypeString, value)
	}
	if value, ok := cuo.mutation.URL(); ok {
		_spec.SetField(comment.FieldURL, field.TypeString, value)
	}
	if cuo.mutation.URLCleared() {
		_spec.ClearField(comment.FieldURL, field.TypeString)
	}
	if value, ok := cuo.mutation.UseHTML(); ok {
		_spec.SetField(comment.FieldUseHTML, field.TypeBool, value)
	}
	if value, ok := cuo.mutation.UseSecret(); ok {
		_spec.SetField(comment.FieldUseSecret, field.TypeBool, value)
	}
	if value, ok := cuo.mutation.UpVoteCount(); ok {
		_spec.SetField(comment.FieldUpVoteCount, field.TypeUint32, value)
	}
	if value, ok := cuo.mutation.AddedUpVoteCount(); ok {
		_spec.AddField(comment.FieldUpVoteCount, field.TypeUint32, value)
	}
	if value, ok := cuo.mutation.DownVoteCount(); ok {
		_spec.SetField(comment.FieldDownVoteCount, field.TypeUint32, value)
	}
	if value, ok := cuo.mutation.AddedDownVoteCount(); ok {
		_spec.AddField(comment.FieldDownVoteCount, field.TypeUint32, value)
	}
	if value, ok := cuo.mutation.UpdatedAt(); ok {
		_spec.SetField(comment.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Comment{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{comment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cuo.mutation.done = true
	return _node, nil
}
