// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/ygpark2/njro/service/comment/ent/comment"
	"github.com/ygpark2/njro/service/comment/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	commentFields := schema.Comment{}.Fields()
	_ = commentFields
	// commentDescBoardID is the schema descriptor for board_id field.
	commentDescBoardID := commentFields[1].Descriptor()
	// comment.BoardIDValidator is a validator for the "board_id" field. It is called by the builders before save.
	comment.BoardIDValidator = commentDescBoardID.Validators[0].(func(string) error)
	// commentDescPostID is the schema descriptor for post_id field.
	commentDescPostID := commentFields[2].Descriptor()
	// comment.PostIDValidator is a validator for the "post_id" field. It is called by the builders before save.
	comment.PostIDValidator = commentDescPostID.Validators[0].(func(string) error)
	// commentDescContentID is the schema descriptor for content_id field.
	commentDescContentID := commentFields[3].Descriptor()
	// comment.DefaultContentID holds the default value on creation for the content_id field.
	comment.DefaultContentID = commentDescContentID.Default.(string)
	// commentDescUserid is the schema descriptor for userid field.
	commentDescUserid := commentFields[4].Descriptor()
	// comment.UseridValidator is a validator for the "userid" field. It is called by the builders before save.
	comment.UseridValidator = commentDescUserid.Validators[0].(func(string) error)
	// commentDescUsername is the schema descriptor for username field.
	commentDescUsername := commentFields[5].Descriptor()
	// comment.DefaultUsername holds the default value on creation for the username field.
	comment.DefaultUsername = commentDescUsername.Default.(string)
	// commentDescNickname is the schema descriptor for nickname field.
	commentDescNickname := commentFields[6].Descriptor()
	// comment.DefaultNickname holds the default value on creation for the nickname field.
	comment.DefaultNickname = commentDescNickname.Default.(string)
	// commentDescEmail is the schema descriptor for email field.
	commentDescEmail := commentFields[7].Descriptor()
	// comment.DefaultEmail holds the default value on creation for the email field.
	comment.DefaultEmail = commentDescEmail.Default.(string)
	// commentDescPassword is the schema descriptor for password field.
	commentDescPassword := commentFields[8].Descriptor()
	// comment.DefaultPassword holds the default value on creation for the password field.
	comment.DefaultPassword = commentDescPassword.Default.(string)
	// commentDescContent is the schema descriptor for content field.
	commentDescContent := commentFields[9].Descriptor()
	// comment.DefaultContent holds the default value on creation for the content field.
	comment.DefaultContent = commentDescContent.Default.(string)
	// commentDescURL is the schema descriptor for url field.
	commentDescURL := commentFields[10].Descriptor()
	// comment.DefaultURL holds the default value on creation for the url field.
	comment.DefaultURL = commentDescURL.Default.(string)
	// commentDescUseHTML is the schema descriptor for use_html field.
	commentDescUseHTML := commentFields[11].Descriptor()
	// comment.DefaultUseHTML holds the default value on creation for the use_html field.
	comment.DefaultUseHTML = commentDescUseHTML.Default.(bool)
	// commentDescUseSecret is the schema descriptor for use_secret field.
	commentDescUseSecret := commentFields[12].Descriptor()
	// comment.DefaultUseSecret holds the default value on creation for the use_secret field.
	comment.DefaultUseSecret = commentDescUseSecret.Default.(bool)
	// commentDescUpVoteCount is the schema descriptor for up_vote_count field.
	commentDescUpVoteCount := commentFields[13].Descriptor()
	// comment.DefaultUpVoteCount holds the default value on creation for the up_vote_count field.
	comment.DefaultUpVoteCount = commentDescUpVoteCount.Default.(uint32)
	// commentDescDownVoteCount is the schema descriptor for down_vote_count field.
	commentDescDownVoteCount := commentFields[14].Descriptor()
	// comment.DefaultDownVoteCount holds the default value on creation for the down_vote_count field.
	comment.DefaultDownVoteCount = commentDescDownVoteCount.Default.(uint32)
	// commentDescCreatedAt is the schema descriptor for created_at field.
	commentDescCreatedAt := commentFields[15].Descriptor()
	// comment.DefaultCreatedAt holds the default value on creation for the created_at field.
	comment.DefaultCreatedAt = commentDescCreatedAt.Default.(func() time.Time)
	// commentDescUpdatedAt is the schema descriptor for updated_at field.
	commentDescUpdatedAt := commentFields[16].Descriptor()
	// comment.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	comment.DefaultUpdatedAt = commentDescUpdatedAt.Default.(func() time.Time)
	// comment.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	comment.UpdateDefaultUpdatedAt = commentDescUpdatedAt.UpdateDefault.(func() time.Time)
	// commentDescID is the schema descriptor for id field.
	commentDescID := commentFields[0].Descriptor()
	// comment.DefaultID holds the default value on creation for the id field.
	comment.DefaultID = commentDescID.Default.(func() uuid.UUID)
}
