// Code generated by entproto. DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: service/account/ent/proto/entpb/entpb.proto

package entpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserRequest_View int32

const (
	GetUserRequest_VIEW_UNSPECIFIED GetUserRequest_View = 0
	GetUserRequest_BASIC            GetUserRequest_View = 1
	GetUserRequest_WITH_EDGE_IDS    GetUserRequest_View = 2
)

// Enum value maps for GetUserRequest_View.
var (
	GetUserRequest_View_name = map[int32]string{
		0: "VIEW_UNSPECIFIED",
		1: "BASIC",
		2: "WITH_EDGE_IDS",
	}
	GetUserRequest_View_value = map[string]int32{
		"VIEW_UNSPECIFIED": 0,
		"BASIC":            1,
		"WITH_EDGE_IDS":    2,
	}
)

func (x GetUserRequest_View) Enum() *GetUserRequest_View {
	p := new(GetUserRequest_View)
	*p = x
	return p
}

func (x GetUserRequest_View) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetUserRequest_View) Descriptor() protoreflect.EnumDescriptor {
	return file_service_account_ent_proto_entpb_entpb_proto_enumTypes[0].Descriptor()
}

func (GetUserRequest_View) Type() protoreflect.EnumType {
	return &file_service_account_ent_proto_entpb_entpb_proto_enumTypes[0]
}

func (x GetUserRequest_View) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetUserRequest_View.Descriptor instead.
func (GetUserRequest_View) EnumDescriptor() ([]byte, []int) {
	return file_service_account_ent_proto_entpb_entpb_proto_rawDescGZIP(), []int{2, 0}
}

type ListUserRequest_View int32

const (
	ListUserRequest_VIEW_UNSPECIFIED ListUserRequest_View = 0
	ListUserRequest_BASIC            ListUserRequest_View = 1
	ListUserRequest_WITH_EDGE_IDS    ListUserRequest_View = 2
)

// Enum value maps for ListUserRequest_View.
var (
	ListUserRequest_View_name = map[int32]string{
		0: "VIEW_UNSPECIFIED",
		1: "BASIC",
		2: "WITH_EDGE_IDS",
	}
	ListUserRequest_View_value = map[string]int32{
		"VIEW_UNSPECIFIED": 0,
		"BASIC":            1,
		"WITH_EDGE_IDS":    2,
	}
)

func (x ListUserRequest_View) Enum() *ListUserRequest_View {
	p := new(ListUserRequest_View)
	*p = x
	return p
}

func (x ListUserRequest_View) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListUserRequest_View) Descriptor() protoreflect.EnumDescriptor {
	return file_service_account_ent_proto_entpb_entpb_proto_enumTypes[1].Descriptor()
}

func (ListUserRequest_View) Type() protoreflect.EnumType {
	return &file_service_account_ent_proto_entpb_entpb_proto_enumTypes[1]
}

func (x ListUserRequest_View) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListUserRequest_View.Descriptor instead.
func (ListUserRequest_View) EnumDescriptor() ([]byte, []int) {
	return file_service_account_ent_proto_entpb_entpb_proto_rawDescGZIP(), []int{5, 0}
}

type User struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            []byte                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                  `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	FirstName     string                  `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                  `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email         string                  `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Password      *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	CreatedAt     *timestamppb.Timestamp  `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp  `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_service_account_ent_proto_entpb_entpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_service_account_ent_proto_entpb_entpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_service_account_ent_proto_entpb_entpb_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPassword() *wrapperspb.StringValue {
	if x != nil {
		return x.Password
	}
	return nil
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_service_account_ent_proto_entpb_entpb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_account_ent_proto_entpb_entpb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_service_account_ent_proto_entpb_entpb_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	View          GetUserRequest_View    `protobuf:"varint,2,opt,name=view,proto3,enum=entpb.GetUserRequest_View" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_service_account_ent_proto_entpb_entpb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_account_ent_proto_entpb_entpb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_service_account_ent_proto_entpb_entpb_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *GetUserRequest) GetView() GetUserRequest_View {
	if x != nil {
		return x.View
	}
	return GetUserRequest_VIEW_UNSPECIFIED
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_service_account_ent_proto_entpb_entpb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_account_ent_proto_entpb_entpb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_service_account_ent_proto_entpb_entpb_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateUserRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_service_account_ent_proto_entpb_entpb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_account_ent_proto_entpb_entpb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_service_account_ent_proto_entpb_entpb_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteUserRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

type ListUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	View          ListUserRequest_View   `protobuf:"varint,3,opt,name=view,proto3,enum=entpb.ListUserRequest_View" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserRequest) Reset() {
	*x = ListUserRequest{}
	mi := &file_service_account_ent_proto_entpb_entpb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserRequest) ProtoMessage() {}

func (x *ListUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_account_ent_proto_entpb_entpb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserRequest.ProtoReflect.Descriptor instead.
func (*ListUserRequest) Descriptor() ([]byte, []int) {
	return file_service_account_ent_proto_entpb_entpb_proto_rawDescGZIP(), []int{5}
}

func (x *ListUserRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListUserRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListUserRequest) GetView() ListUserRequest_View {
	if x != nil {
		return x.View
	}
	return ListUserRequest_VIEW_UNSPECIFIED
}

type ListUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserList      []*User                `protobuf:"bytes,1,rep,name=user_list,json=userList,proto3" json:"user_list,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserResponse) Reset() {
	*x = ListUserResponse{}
	mi := &file_service_account_ent_proto_entpb_entpb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserResponse) ProtoMessage() {}

func (x *ListUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_account_ent_proto_entpb_entpb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserResponse.ProtoReflect.Descriptor instead.
func (*ListUserResponse) Descriptor() ([]byte, []int) {
	return file_service_account_ent_proto_entpb_entpb_proto_rawDescGZIP(), []int{6}
}

func (x *ListUserResponse) GetUserList() []*User {
	if x != nil {
		return x.UserList
	}
	return nil
}

func (x *ListUserResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type BatchCreateUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*CreateUserRequest   `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateUsersRequest) Reset() {
	*x = BatchCreateUsersRequest{}
	mi := &file_service_account_ent_proto_entpb_entpb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateUsersRequest) ProtoMessage() {}

func (x *BatchCreateUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_account_ent_proto_entpb_entpb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateUsersRequest.ProtoReflect.Descriptor instead.
func (*BatchCreateUsersRequest) Descriptor() ([]byte, []int) {
	return file_service_account_ent_proto_entpb_entpb_proto_rawDescGZIP(), []int{7}
}

func (x *BatchCreateUsersRequest) GetRequests() []*CreateUserRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type BatchCreateUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateUsersResponse) Reset() {
	*x = BatchCreateUsersResponse{}
	mi := &file_service_account_ent_proto_entpb_entpb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateUsersResponse) ProtoMessage() {}

func (x *BatchCreateUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_account_ent_proto_entpb_entpb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateUsersResponse.ProtoReflect.Descriptor instead.
func (*BatchCreateUsersResponse) Descriptor() ([]byte, []int) {
	return file_service_account_ent_proto_entpb_entpb_proto_rawDescGZIP(), []int{8}
}

func (x *BatchCreateUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_service_account_ent_proto_entpb_entpb_proto protoreflect.FileDescriptor

const file_service_account_ent_proto_entpb_entpb_proto_rawDesc = "" +
	"\n" +
	"+service/account/ent/proto/entpb/entpb.proto\x12\x05entpb\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xb4\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x128\n" +
	"\bpassword\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueR\bpassword\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"4\n" +
	"\x11CreateUserRequest\x12\x1f\n" +
	"\x04user\x18\x01 \x01(\v2\v.entpb.UserR\x04user\"\x8c\x01\n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12.\n" +
	"\x04view\x18\x02 \x01(\x0e2\x1a.entpb.GetUserRequest.ViewR\x04view\":\n" +
	"\x04View\x12\x14\n" +
	"\x10VIEW_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05BASIC\x10\x01\x12\x11\n" +
	"\rWITH_EDGE_IDS\x10\x02\"4\n" +
	"\x11UpdateUserRequest\x12\x1f\n" +
	"\x04user\x18\x01 \x01(\v2\v.entpb.UserR\x04user\"#\n" +
	"\x11DeleteUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\"\xba\x01\n" +
	"\x0fListUserRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12/\n" +
	"\x04view\x18\x03 \x01(\x0e2\x1b.entpb.ListUserRequest.ViewR\x04view\":\n" +
	"\x04View\x12\x14\n" +
	"\x10VIEW_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05BASIC\x10\x01\x12\x11\n" +
	"\rWITH_EDGE_IDS\x10\x02\"d\n" +
	"\x10ListUserResponse\x12(\n" +
	"\tuser_list\x18\x01 \x03(\v2\v.entpb.UserR\buserList\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"O\n" +
	"\x17BatchCreateUsersRequest\x124\n" +
	"\brequests\x18\x01 \x03(\v2\x18.entpb.CreateUserRequestR\brequests\"=\n" +
	"\x18BatchCreateUsersResponse\x12!\n" +
	"\x05users\x18\x01 \x03(\v2\v.entpb.UserR\x05users2\xdf\x02\n" +
	"\vUserService\x12/\n" +
	"\x06Create\x12\x18.entpb.CreateUserRequest\x1a\v.entpb.User\x12)\n" +
	"\x03Get\x12\x15.entpb.GetUserRequest\x1a\v.entpb.User\x12/\n" +
	"\x06Update\x12\x18.entpb.UpdateUserRequest\x1a\v.entpb.User\x12:\n" +
	"\x06Delete\x12\x18.entpb.DeleteUserRequest\x1a\x16.google.protobuf.Empty\x127\n" +
	"\x04List\x12\x16.entpb.ListUserRequest\x1a\x17.entpb.ListUserResponse\x12N\n" +
	"\vBatchCreate\x12\x1e.entpb.BatchCreateUsersRequest\x1a\x1f.entpb.BatchCreateUsersResponseB9Z7github.com/ygpark2/njro/service/account/ent/proto/entpbb\x06proto3"

var (
	file_service_account_ent_proto_entpb_entpb_proto_rawDescOnce sync.Once
	file_service_account_ent_proto_entpb_entpb_proto_rawDescData []byte
)

func file_service_account_ent_proto_entpb_entpb_proto_rawDescGZIP() []byte {
	file_service_account_ent_proto_entpb_entpb_proto_rawDescOnce.Do(func() {
		file_service_account_ent_proto_entpb_entpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_account_ent_proto_entpb_entpb_proto_rawDesc), len(file_service_account_ent_proto_entpb_entpb_proto_rawDesc)))
	})
	return file_service_account_ent_proto_entpb_entpb_proto_rawDescData
}

var file_service_account_ent_proto_entpb_entpb_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_service_account_ent_proto_entpb_entpb_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_service_account_ent_proto_entpb_entpb_proto_goTypes = []any{
	(GetUserRequest_View)(0),         // 0: entpb.GetUserRequest.View
	(ListUserRequest_View)(0),        // 1: entpb.ListUserRequest.View
	(*User)(nil),                     // 2: entpb.User
	(*CreateUserRequest)(nil),        // 3: entpb.CreateUserRequest
	(*GetUserRequest)(nil),           // 4: entpb.GetUserRequest
	(*UpdateUserRequest)(nil),        // 5: entpb.UpdateUserRequest
	(*DeleteUserRequest)(nil),        // 6: entpb.DeleteUserRequest
	(*ListUserRequest)(nil),          // 7: entpb.ListUserRequest
	(*ListUserResponse)(nil),         // 8: entpb.ListUserResponse
	(*BatchCreateUsersRequest)(nil),  // 9: entpb.BatchCreateUsersRequest
	(*BatchCreateUsersResponse)(nil), // 10: entpb.BatchCreateUsersResponse
	(*wrapperspb.StringValue)(nil),   // 11: google.protobuf.StringValue
	(*timestamppb.Timestamp)(nil),    // 12: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),            // 13: google.protobuf.Empty
}
var file_service_account_ent_proto_entpb_entpb_proto_depIdxs = []int32{
	11, // 0: entpb.User.password:type_name -> google.protobuf.StringValue
	12, // 1: entpb.User.created_at:type_name -> google.protobuf.Timestamp
	12, // 2: entpb.User.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 3: entpb.CreateUserRequest.user:type_name -> entpb.User
	0,  // 4: entpb.GetUserRequest.view:type_name -> entpb.GetUserRequest.View
	2,  // 5: entpb.UpdateUserRequest.user:type_name -> entpb.User
	1,  // 6: entpb.ListUserRequest.view:type_name -> entpb.ListUserRequest.View
	2,  // 7: entpb.ListUserResponse.user_list:type_name -> entpb.User
	3,  // 8: entpb.BatchCreateUsersRequest.requests:type_name -> entpb.CreateUserRequest
	2,  // 9: entpb.BatchCreateUsersResponse.users:type_name -> entpb.User
	3,  // 10: entpb.UserService.Create:input_type -> entpb.CreateUserRequest
	4,  // 11: entpb.UserService.Get:input_type -> entpb.GetUserRequest
	5,  // 12: entpb.UserService.Update:input_type -> entpb.UpdateUserRequest
	6,  // 13: entpb.UserService.Delete:input_type -> entpb.DeleteUserRequest
	7,  // 14: entpb.UserService.List:input_type -> entpb.ListUserRequest
	9,  // 15: entpb.UserService.BatchCreate:input_type -> entpb.BatchCreateUsersRequest
	2,  // 16: entpb.UserService.Create:output_type -> entpb.User
	2,  // 17: entpb.UserService.Get:output_type -> entpb.User
	2,  // 18: entpb.UserService.Update:output_type -> entpb.User
	13, // 19: entpb.UserService.Delete:output_type -> google.protobuf.Empty
	8,  // 20: entpb.UserService.List:output_type -> entpb.ListUserResponse
	10, // 21: entpb.UserService.BatchCreate:output_type -> entpb.BatchCreateUsersResponse
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_service_account_ent_proto_entpb_entpb_proto_init() }
func file_service_account_ent_proto_entpb_entpb_proto_init() {
	if File_service_account_ent_proto_entpb_entpb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_account_ent_proto_entpb_entpb_proto_rawDesc), len(file_service_account_ent_proto_entpb_entpb_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_account_ent_proto_entpb_entpb_proto_goTypes,
		DependencyIndexes: file_service_account_ent_proto_entpb_entpb_proto_depIdxs,
		EnumInfos:         file_service_account_ent_proto_entpb_entpb_proto_enumTypes,
		MessageInfos:      file_service_account_ent_proto_entpb_entpb_proto_msgTypes,
	}.Build()
	File_service_account_ent_proto_entpb_entpb_proto = out.File
	file_service_account_ent_proto_entpb_entpb_proto_goTypes = nil
	file_service_account_ent_proto_entpb_entpb_proto_depIdxs = nil
}
