// Code generated by ent, DO NOT EDIT.

package comment

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the comment type in the database.
	Label = "comment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBoardID holds the string denoting the board_id field in the database.
	FieldBoardID = "board_id"
	// FieldPostID holds the string denoting the post_id field in the database.
	FieldPostID = "post_id"
	// FieldContentID holds the string denoting the content_id field in the database.
	FieldContentID = "content_id"
	// FieldUserid holds the string denoting the userid field in the database.
	FieldUserid = "userid"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldNickname holds the string denoting the nickname field in the database.
	FieldNickname = "nickname"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldUseHTML holds the string denoting the use_html field in the database.
	FieldUseHTML = "use_html"
	// FieldUseSecret holds the string denoting the use_secret field in the database.
	FieldUseSecret = "use_secret"
	// FieldUpVoteCount holds the string denoting the up_vote_count field in the database.
	FieldUpVoteCount = "up_vote_count"
	// FieldDownVoteCount holds the string denoting the down_vote_count field in the database.
	FieldDownVoteCount = "down_vote_count"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the comment in the database.
	Table = "comments"
)

// Columns holds all SQL columns for comment fields.
var Columns = []string{
	FieldID,
	FieldBoardID,
	FieldPostID,
	FieldContentID,
	FieldUserid,
	FieldUsername,
	FieldNickname,
	FieldEmail,
	FieldPassword,
	FieldContent,
	FieldURL,
	FieldUseHTML,
	FieldUseSecret,
	FieldUpVoteCount,
	FieldDownVoteCount,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// BoardIDValidator is a validator for the "board_id" field. It is called by the builders before save.
	BoardIDValidator func(string) error
	// PostIDValidator is a validator for the "post_id" field. It is called by the builders before save.
	PostIDValidator func(string) error
	// DefaultContentID holds the default value on creation for the "content_id" field.
	DefaultContentID string
	// UseridValidator is a validator for the "userid" field. It is called by the builders before save.
	UseridValidator func(string) error
	// DefaultUsername holds the default value on creation for the "username" field.
	DefaultUsername string
	// DefaultNickname holds the default value on creation for the "nickname" field.
	DefaultNickname string
	// DefaultEmail holds the default value on creation for the "email" field.
	DefaultEmail string
	// DefaultPassword holds the default value on creation for the "password" field.
	DefaultPassword string
	// DefaultContent holds the default value on creation for the "content" field.
	DefaultContent string
	// DefaultURL holds the default value on creation for the "url" field.
	DefaultURL string
	// DefaultUseHTML holds the default value on creation for the "use_html" field.
	DefaultUseHTML bool
	// DefaultUseSecret holds the default value on creation for the "use_secret" field.
	DefaultUseSecret bool
	// DefaultUpVoteCount holds the default value on creation for the "up_vote_count" field.
	DefaultUpVoteCount uint32
	// DefaultDownVoteCount holds the default value on creation for the "down_vote_count" field.
	DefaultDownVoteCount uint32
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Comment queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByBoardID orders the results by the board_id field.
func ByBoardID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBoardID, opts...).ToFunc()
}

// ByPostID orders the results by the post_id field.
func ByPostID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPostID, opts...).ToFunc()
}

// ByContentID orders the results by the content_id field.
func ByContentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContentID, opts...).ToFunc()
}

// ByUserid orders the results by the userid field.
func ByUserid(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserid, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByNickname orders the results by the nickname field.
func ByNickname(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNickname, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByPassword orders the results by the password field.
func ByPassword(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPassword, opts...).ToFunc()
}

// ByContent orders the results by the content field.
func ByContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContent, opts...).ToFunc()
}

// ByURL orders the results by the url field.
func ByURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldURL, opts...).ToFunc()
}

// ByUseHTML orders the results by the use_html field.
func ByUseHTML(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUseHTML, opts...).ToFunc()
}

// ByUseSecret orders the results by the use_secret field.
func ByUseSecret(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUseSecret, opts...).ToFunc()
}

// ByUpVoteCount orders the results by the up_vote_count field.
func ByUpVoteCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpVoteCount, opts...).ToFunc()
}

// ByDownVoteCount orders the results by the down_vote_count field.
func ByDownVoteCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDownVoteCount, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
