// Code generated by entproto. DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: service/comment/ent/proto/entpb/entpb.proto

package entpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCommentRequest_View int32

const (
	GetCommentRequest_VIEW_UNSPECIFIED GetCommentRequest_View = 0
	GetCommentRequest_BASIC            GetCommentRequest_View = 1
	GetCommentRequest_WITH_EDGE_IDS    GetCommentRequest_View = 2
)

// Enum value maps for GetCommentRequest_View.
var (
	GetCommentRequest_View_name = map[int32]string{
		0: "VIEW_UNSPECIFIED",
		1: "BASIC",
		2: "WITH_EDGE_IDS",
	}
	GetCommentRequest_View_value = map[string]int32{
		"VIEW_UNSPECIFIED": 0,
		"BASIC":            1,
		"WITH_EDGE_IDS":    2,
	}
)

func (x GetCommentRequest_View) Enum() *GetCommentRequest_View {
	p := new(GetCommentRequest_View)
	*p = x
	return p
}

func (x GetCommentRequest_View) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetCommentRequest_View) Descriptor() protoreflect.EnumDescriptor {
	return file_service_comment_ent_proto_entpb_entpb_proto_enumTypes[0].Descriptor()
}

func (GetCommentRequest_View) Type() protoreflect.EnumType {
	return &file_service_comment_ent_proto_entpb_entpb_proto_enumTypes[0]
}

func (x GetCommentRequest_View) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetCommentRequest_View.Descriptor instead.
func (GetCommentRequest_View) EnumDescriptor() ([]byte, []int) {
	return file_service_comment_ent_proto_entpb_entpb_proto_rawDescGZIP(), []int{2, 0}
}

type ListCommentRequest_View int32

const (
	ListCommentRequest_VIEW_UNSPECIFIED ListCommentRequest_View = 0
	ListCommentRequest_BASIC            ListCommentRequest_View = 1
	ListCommentRequest_WITH_EDGE_IDS    ListCommentRequest_View = 2
)

// Enum value maps for ListCommentRequest_View.
var (
	ListCommentRequest_View_name = map[int32]string{
		0: "VIEW_UNSPECIFIED",
		1: "BASIC",
		2: "WITH_EDGE_IDS",
	}
	ListCommentRequest_View_value = map[string]int32{
		"VIEW_UNSPECIFIED": 0,
		"BASIC":            1,
		"WITH_EDGE_IDS":    2,
	}
)

func (x ListCommentRequest_View) Enum() *ListCommentRequest_View {
	p := new(ListCommentRequest_View)
	*p = x
	return p
}

func (x ListCommentRequest_View) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListCommentRequest_View) Descriptor() protoreflect.EnumDescriptor {
	return file_service_comment_ent_proto_entpb_entpb_proto_enumTypes[1].Descriptor()
}

func (ListCommentRequest_View) Type() protoreflect.EnumType {
	return &file_service_comment_ent_proto_entpb_entpb_proto_enumTypes[1]
}

func (x ListCommentRequest_View) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListCommentRequest_View.Descriptor instead.
func (ListCommentRequest_View) EnumDescriptor() ([]byte, []int) {
	return file_service_comment_ent_proto_entpb_entpb_proto_rawDescGZIP(), []int{5, 0}
}

type Comment struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            []byte                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BoardId       string                  `protobuf:"bytes,2,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	PostId        string                  `protobuf:"bytes,3,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	ContentId     string                  `protobuf:"bytes,4,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	Userid        string                  `protobuf:"bytes,5,opt,name=userid,proto3" json:"userid,omitempty"`
	Username      string                  `protobuf:"bytes,6,opt,name=username,proto3" json:"username,omitempty"`
	Nickname      string                  `protobuf:"bytes,7,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Email         string                  `protobuf:"bytes,8,opt,name=email,proto3" json:"email,omitempty"`
	Password      *wrapperspb.StringValue `protobuf:"bytes,9,opt,name=password,proto3" json:"password,omitempty"`
	Content       string                  `protobuf:"bytes,10,opt,name=content,proto3" json:"content,omitempty"`
	Url           *wrapperspb.StringValue `protobuf:"bytes,11,opt,name=url,proto3" json:"url,omitempty"`
	UseHtml       bool                    `protobuf:"varint,12,opt,name=use_html,json=useHtml,proto3" json:"use_html,omitempty"`
	UseSecret     bool                    `protobuf:"varint,13,opt,name=use_secret,json=useSecret,proto3" json:"use_secret,omitempty"`
	UpVoteCount   uint32                  `protobuf:"varint,14,opt,name=up_vote_count,json=upVoteCount,proto3" json:"up_vote_count,omitempty"`
	DownVoteCount uint32                  `protobuf:"varint,15,opt,name=down_vote_count,json=downVoteCount,proto3" json:"down_vote_count,omitempty"`
	CreatedAt     *timestamppb.Timestamp  `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp  `protobuf:"bytes,17,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_service_comment_ent_proto_entpb_entpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_service_comment_ent_proto_entpb_entpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_service_comment_ent_proto_entpb_entpb_proto_rawDescGZIP(), []int{0}
}

func (x *Comment) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Comment) GetBoardId() string {
	if x != nil {
		return x.BoardId
	}
	return ""
}

func (x *Comment) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *Comment) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *Comment) GetUserid() string {
	if x != nil {
		return x.Userid
	}
	return ""
}

func (x *Comment) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Comment) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *Comment) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Comment) GetPassword() *wrapperspb.StringValue {
	if x != nil {
		return x.Password
	}
	return nil
}

func (x *Comment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Comment) GetUrl() *wrapperspb.StringValue {
	if x != nil {
		return x.Url
	}
	return nil
}

func (x *Comment) GetUseHtml() bool {
	if x != nil {
		return x.UseHtml
	}
	return false
}

func (x *Comment) GetUseSecret() bool {
	if x != nil {
		return x.UseSecret
	}
	return false
}

func (x *Comment) GetUpVoteCount() uint32 {
	if x != nil {
		return x.UpVoteCount
	}
	return 0
}

func (x *Comment) GetDownVoteCount() uint32 {
	if x != nil {
		return x.DownVoteCount
	}
	return 0
}

func (x *Comment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Comment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       *Comment               `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentRequest) Reset() {
	*x = CreateCommentRequest{}
	mi := &file_service_comment_ent_proto_entpb_entpb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentRequest) ProtoMessage() {}

func (x *CreateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_comment_ent_proto_entpb_entpb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentRequest.ProtoReflect.Descriptor instead.
func (*CreateCommentRequest) Descriptor() ([]byte, []int) {
	return file_service_comment_ent_proto_entpb_entpb_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCommentRequest) GetComment() *Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

type GetCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	View          GetCommentRequest_View `protobuf:"varint,2,opt,name=view,proto3,enum=entpb.GetCommentRequest_View" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentRequest) Reset() {
	*x = GetCommentRequest{}
	mi := &file_service_comment_ent_proto_entpb_entpb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentRequest) ProtoMessage() {}

func (x *GetCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_comment_ent_proto_entpb_entpb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentRequest.ProtoReflect.Descriptor instead.
func (*GetCommentRequest) Descriptor() ([]byte, []int) {
	return file_service_comment_ent_proto_entpb_entpb_proto_rawDescGZIP(), []int{2}
}

func (x *GetCommentRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *GetCommentRequest) GetView() GetCommentRequest_View {
	if x != nil {
		return x.View
	}
	return GetCommentRequest_VIEW_UNSPECIFIED
}

type UpdateCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       *Comment               `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommentRequest) Reset() {
	*x = UpdateCommentRequest{}
	mi := &file_service_comment_ent_proto_entpb_entpb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommentRequest) ProtoMessage() {}

func (x *UpdateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_comment_ent_proto_entpb_entpb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommentRequest.ProtoReflect.Descriptor instead.
func (*UpdateCommentRequest) Descriptor() ([]byte, []int) {
	return file_service_comment_ent_proto_entpb_entpb_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateCommentRequest) GetComment() *Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

type DeleteCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentRequest) Reset() {
	*x = DeleteCommentRequest{}
	mi := &file_service_comment_ent_proto_entpb_entpb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentRequest) ProtoMessage() {}

func (x *DeleteCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_comment_ent_proto_entpb_entpb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommentRequest) Descriptor() ([]byte, []int) {
	return file_service_comment_ent_proto_entpb_entpb_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteCommentRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

type ListCommentRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	PageSize      int32                   `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                  `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	View          ListCommentRequest_View `protobuf:"varint,3,opt,name=view,proto3,enum=entpb.ListCommentRequest_View" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentRequest) Reset() {
	*x = ListCommentRequest{}
	mi := &file_service_comment_ent_proto_entpb_entpb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentRequest) ProtoMessage() {}

func (x *ListCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_comment_ent_proto_entpb_entpb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentRequest.ProtoReflect.Descriptor instead.
func (*ListCommentRequest) Descriptor() ([]byte, []int) {
	return file_service_comment_ent_proto_entpb_entpb_proto_rawDescGZIP(), []int{5}
}

func (x *ListCommentRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCommentRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListCommentRequest) GetView() ListCommentRequest_View {
	if x != nil {
		return x.View
	}
	return ListCommentRequest_VIEW_UNSPECIFIED
}

type ListCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentList   []*Comment             `protobuf:"bytes,1,rep,name=comment_list,json=commentList,proto3" json:"comment_list,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentResponse) Reset() {
	*x = ListCommentResponse{}
	mi := &file_service_comment_ent_proto_entpb_entpb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentResponse) ProtoMessage() {}

func (x *ListCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_comment_ent_proto_entpb_entpb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentResponse.ProtoReflect.Descriptor instead.
func (*ListCommentResponse) Descriptor() ([]byte, []int) {
	return file_service_comment_ent_proto_entpb_entpb_proto_rawDescGZIP(), []int{6}
}

func (x *ListCommentResponse) GetCommentList() []*Comment {
	if x != nil {
		return x.CommentList
	}
	return nil
}

func (x *ListCommentResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type BatchCreateCommentsRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Requests      []*CreateCommentRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateCommentsRequest) Reset() {
	*x = BatchCreateCommentsRequest{}
	mi := &file_service_comment_ent_proto_entpb_entpb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateCommentsRequest) ProtoMessage() {}

func (x *BatchCreateCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_comment_ent_proto_entpb_entpb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateCommentsRequest.ProtoReflect.Descriptor instead.
func (*BatchCreateCommentsRequest) Descriptor() ([]byte, []int) {
	return file_service_comment_ent_proto_entpb_entpb_proto_rawDescGZIP(), []int{7}
}

func (x *BatchCreateCommentsRequest) GetRequests() []*CreateCommentRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type BatchCreateCommentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*Comment             `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateCommentsResponse) Reset() {
	*x = BatchCreateCommentsResponse{}
	mi := &file_service_comment_ent_proto_entpb_entpb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateCommentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateCommentsResponse) ProtoMessage() {}

func (x *BatchCreateCommentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_comment_ent_proto_entpb_entpb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateCommentsResponse.ProtoReflect.Descriptor instead.
func (*BatchCreateCommentsResponse) Descriptor() ([]byte, []int) {
	return file_service_comment_ent_proto_entpb_entpb_proto_rawDescGZIP(), []int{8}
}

func (x *BatchCreateCommentsResponse) GetComments() []*Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

var File_service_comment_ent_proto_entpb_entpb_proto protoreflect.FileDescriptor

const file_service_comment_ent_proto_entpb_entpb_proto_rawDesc = "" +
	"\n" +
	"+service/comment/ent/proto/entpb/entpb.proto\x12\x05entpb\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xd2\x04\n" +
	"\aComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x19\n" +
	"\bboard_id\x18\x02 \x01(\tR\aboardId\x12\x17\n" +
	"\apost_id\x18\x03 \x01(\tR\x06postId\x12\x1d\n" +
	"\n" +
	"content_id\x18\x04 \x01(\tR\tcontentId\x12\x16\n" +
	"\x06userid\x18\x05 \x01(\tR\x06userid\x12\x1a\n" +
	"\busername\x18\x06 \x01(\tR\busername\x12\x1a\n" +
	"\bnickname\x18\a \x01(\tR\bnickname\x12\x14\n" +
	"\x05email\x18\b \x01(\tR\x05email\x128\n" +
	"\bpassword\x18\t \x01(\v2\x1c.google.protobuf.StringValueR\bpassword\x12\x18\n" +
	"\acontent\x18\n" +
	" \x01(\tR\acontent\x12.\n" +
	"\x03url\x18\v \x01(\v2\x1c.google.protobuf.StringValueR\x03url\x12\x19\n" +
	"\buse_html\x18\f \x01(\bR\auseHtml\x12\x1d\n" +
	"\n" +
	"use_secret\x18\r \x01(\bR\tuseSecret\x12\"\n" +
	"\rup_vote_count\x18\x0e \x01(\rR\vupVoteCount\x12&\n" +
	"\x0fdown_vote_count\x18\x0f \x01(\rR\rdownVoteCount\x129\n" +
	"\n" +
	"created_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"@\n" +
	"\x14CreateCommentRequest\x12(\n" +
	"\acomment\x18\x01 \x01(\v2\x0e.entpb.CommentR\acomment\"\x92\x01\n" +
	"\x11GetCommentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x121\n" +
	"\x04view\x18\x02 \x01(\x0e2\x1d.entpb.GetCommentRequest.ViewR\x04view\":\n" +
	"\x04View\x12\x14\n" +
	"\x10VIEW_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05BASIC\x10\x01\x12\x11\n" +
	"\rWITH_EDGE_IDS\x10\x02\"@\n" +
	"\x14UpdateCommentRequest\x12(\n" +
	"\acomment\x18\x01 \x01(\v2\x0e.entpb.CommentR\acomment\"&\n" +
	"\x14DeleteCommentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\"\xc0\x01\n" +
	"\x12ListCommentRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x122\n" +
	"\x04view\x18\x03 \x01(\x0e2\x1e.entpb.ListCommentRequest.ViewR\x04view\":\n" +
	"\x04View\x12\x14\n" +
	"\x10VIEW_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05BASIC\x10\x01\x12\x11\n" +
	"\rWITH_EDGE_IDS\x10\x02\"p\n" +
	"\x13ListCommentResponse\x121\n" +
	"\fcomment_list\x18\x01 \x03(\v2\x0e.entpb.CommentR\vcommentList\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"U\n" +
	"\x1aBatchCreateCommentsRequest\x127\n" +
	"\brequests\x18\x01 \x03(\v2\x1b.entpb.CreateCommentRequestR\brequests\"I\n" +
	"\x1bBatchCreateCommentsResponse\x12*\n" +
	"\bcomments\x18\x01 \x03(\v2\x0e.entpb.CommentR\bcomments2\x83\x03\n" +
	"\x0eCommentService\x125\n" +
	"\x06Create\x12\x1b.entpb.CreateCommentRequest\x1a\x0e.entpb.Comment\x12/\n" +
	"\x03Get\x12\x18.entpb.GetCommentRequest\x1a\x0e.entpb.Comment\x125\n" +
	"\x06Update\x12\x1b.entpb.UpdateCommentRequest\x1a\x0e.entpb.Comment\x12=\n" +
	"\x06Delete\x12\x1b.entpb.DeleteCommentRequest\x1a\x16.google.protobuf.Empty\x12=\n" +
	"\x04List\x12\x19.entpb.ListCommentRequest\x1a\x1a.entpb.ListCommentResponse\x12T\n" +
	"\vBatchCreate\x12!.entpb.BatchCreateCommentsRequest\x1a\".entpb.BatchCreateCommentsResponseB9Z7github.com/ygpark2/njro/service/comment/ent/proto/entpbb\x06proto3"

var (
	file_service_comment_ent_proto_entpb_entpb_proto_rawDescOnce sync.Once
	file_service_comment_ent_proto_entpb_entpb_proto_rawDescData []byte
)

func file_service_comment_ent_proto_entpb_entpb_proto_rawDescGZIP() []byte {
	file_service_comment_ent_proto_entpb_entpb_proto_rawDescOnce.Do(func() {
		file_service_comment_ent_proto_entpb_entpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_comment_ent_proto_entpb_entpb_proto_rawDesc), len(file_service_comment_ent_proto_entpb_entpb_proto_rawDesc)))
	})
	return file_service_comment_ent_proto_entpb_entpb_proto_rawDescData
}

var file_service_comment_ent_proto_entpb_entpb_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_service_comment_ent_proto_entpb_entpb_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_service_comment_ent_proto_entpb_entpb_proto_goTypes = []any{
	(GetCommentRequest_View)(0),         // 0: entpb.GetCommentRequest.View
	(ListCommentRequest_View)(0),        // 1: entpb.ListCommentRequest.View
	(*Comment)(nil),                     // 2: entpb.Comment
	(*CreateCommentRequest)(nil),        // 3: entpb.CreateCommentRequest
	(*GetCommentRequest)(nil),           // 4: entpb.GetCommentRequest
	(*UpdateCommentRequest)(nil),        // 5: entpb.UpdateCommentRequest
	(*DeleteCommentRequest)(nil),        // 6: entpb.DeleteCommentRequest
	(*ListCommentRequest)(nil),          // 7: entpb.ListCommentRequest
	(*ListCommentResponse)(nil),         // 8: entpb.ListCommentResponse
	(*BatchCreateCommentsRequest)(nil),  // 9: entpb.BatchCreateCommentsRequest
	(*BatchCreateCommentsResponse)(nil), // 10: entpb.BatchCreateCommentsResponse
	(*wrapperspb.StringValue)(nil),      // 11: google.protobuf.StringValue
	(*timestamppb.Timestamp)(nil),       // 12: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),               // 13: google.protobuf.Empty
}
var file_service_comment_ent_proto_entpb_entpb_proto_depIdxs = []int32{
	11, // 0: entpb.Comment.password:type_name -> google.protobuf.StringValue
	11, // 1: entpb.Comment.url:type_name -> google.protobuf.StringValue
	12, // 2: entpb.Comment.created_at:type_name -> google.protobuf.Timestamp
	12, // 3: entpb.Comment.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 4: entpb.CreateCommentRequest.comment:type_name -> entpb.Comment
	0,  // 5: entpb.GetCommentRequest.view:type_name -> entpb.GetCommentRequest.View
	2,  // 6: entpb.UpdateCommentRequest.comment:type_name -> entpb.Comment
	1,  // 7: entpb.ListCommentRequest.view:type_name -> entpb.ListCommentRequest.View
	2,  // 8: entpb.ListCommentResponse.comment_list:type_name -> entpb.Comment
	3,  // 9: entpb.BatchCreateCommentsRequest.requests:type_name -> entpb.CreateCommentRequest
	2,  // 10: entpb.BatchCreateCommentsResponse.comments:type_name -> entpb.Comment
	3,  // 11: entpb.CommentService.Create:input_type -> entpb.CreateCommentRequest
	4,  // 12: entpb.CommentService.Get:input_type -> entpb.GetCommentRequest
	5,  // 13: entpb.CommentService.Update:input_type -> entpb.UpdateCommentRequest
	6,  // 14: entpb.CommentService.Delete:input_type -> entpb.DeleteCommentRequest
	7,  // 15: entpb.CommentService.List:input_type -> entpb.ListCommentRequest
	9,  // 16: entpb.CommentService.BatchCreate:input_type -> entpb.BatchCreateCommentsRequest
	2,  // 17: entpb.CommentService.Create:output_type -> entpb.Comment
	2,  // 18: entpb.CommentService.Get:output_type -> entpb.Comment
	2,  // 19: entpb.CommentService.Update:output_type -> entpb.Comment
	13, // 20: entpb.CommentService.Delete:output_type -> google.protobuf.Empty
	8,  // 21: entpb.CommentService.List:output_type -> entpb.ListCommentResponse
	10, // 22: entpb.CommentService.BatchCreate:output_type -> entpb.BatchCreateCommentsResponse
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_service_comment_ent_proto_entpb_entpb_proto_init() }
func file_service_comment_ent_proto_entpb_entpb_proto_init() {
	if File_service_comment_ent_proto_entpb_entpb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_comment_ent_proto_entpb_entpb_proto_rawDesc), len(file_service_comment_ent_proto_entpb_entpb_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_comment_ent_proto_entpb_entpb_proto_goTypes,
		DependencyIndexes: file_service_comment_ent_proto_entpb_entpb_proto_depIdxs,
		EnumInfos:         file_service_comment_ent_proto_entpb_entpb_proto_enumTypes,
		MessageInfos:      file_service_comment_ent_proto_entpb_entpb_proto_msgTypes,
	}.Build()
	File_service_comment_ent_proto_entpb_entpb_proto = out.File
	file_service_comment_ent_proto_entpb_entpb_proto_goTypes = nil
	file_service_comment_ent_proto_entpb_entpb_proto_depIdxs = nil
}
