// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package registry

import (
	"github.com/micro/micro/v3/service"
	"github.com/ygpark2/mboard/service/board/handler"
	"github.com/ygpark2/mboard/shared/config"
)

// Injectors from wire.go:

// NewContainer - create new Container
func NewContainer() *Container {
	configuration := config.GetConfig()
	boardRepository := BuildBoardRepository(configuration)
	event := &service.Event{}
	boardServiceHandler := handler.NewBoardHandler(boardRepository, event)
	container := &Container{
		BoardRepository: boardRepository,
		BoardHandler:    boardServiceHandler,
	}
	return container
}
