// Code generated by protoc-gen-entgrpc. DO NOT EDIT.
package entpb

import (
	context "context"
	base64 "encoding/base64"
	entproto "entgo.io/contrib/entproto"
	runtime "entgo.io/contrib/entproto/runtime"
	sqlgraph "entgo.io/ent/dialect/sql/sqlgraph"
	fmt "fmt"
	uuid "github.com/google/uuid"
	ent "github.com/ygpark2/njro/service/board/ent"
	board "github.com/ygpark2/njro/service/board/ent/board"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

// BoardService implements BoardServiceServer
type BoardService struct {
	client *ent.Client
	UnimplementedBoardServiceServer
}

// NewBoardService returns a new BoardService
func NewBoardService(client *ent.Client) *BoardService {
	return &BoardService{
		client: client,
	}
}

// toProtoBoard transforms the ent type to the pb type
func toProtoBoard(e *ent.Board) (*Board, error) {
	v := &Board{}
	created_at := timestamppb.New(e.CreatedAt)
	v.CreatedAt = created_at
	description := e.Description
	v.Description = description
	id, err := e.ID.MarshalBinary()
	if err != nil {
		return nil, err
	}
	v.Id = id
	mobile_title := e.MobileTitle
	v.MobileTitle = mobile_title
	notices := e.Notices
	v.Notices = notices
	_order := e.Order
	v.Order = _order
	search := e.Search
	v.Search = search
	title := e.Title
	v.Title = title
	updated_at := timestamppb.New(e.UpdatedAt)
	v.UpdatedAt = updated_at
	return v, nil
}

// toProtoBoardList transforms a list of ent type to a list of pb type
func toProtoBoardList(e []*ent.Board) ([]*Board, error) {
	var pbList []*Board
	for _, entEntity := range e {
		pbEntity, err := toProtoBoard(entEntity)
		if err != nil {
			return nil, status.Errorf(codes.Internal, "internal error: %s", err)
		}
		pbList = append(pbList, pbEntity)
	}
	return pbList, nil
}

// Create implements BoardServiceServer.Create
func (svc *BoardService) Create(ctx context.Context, req *CreateBoardRequest) (*Board, error) {
	board := req.GetBoard()
	m, err := svc.createBuilder(board)
	if err != nil {
		return nil, err
	}
	res, err := m.Save(ctx)
	switch {
	case err == nil:
		proto, err := toProtoBoard(res)
		if err != nil {
			return nil, status.Errorf(codes.Internal, "internal error: %s", err)
		}
		return proto, nil
	case sqlgraph.IsUniqueConstraintError(err):
		return nil, status.Errorf(codes.AlreadyExists, "already exists: %s", err)
	case ent.IsConstraintError(err):
		return nil, status.Errorf(codes.InvalidArgument, "invalid argument: %s", err)
	default:
		return nil, status.Errorf(codes.Internal, "internal error: %s", err)
	}

}

// Get implements BoardServiceServer.Get
func (svc *BoardService) Get(ctx context.Context, req *GetBoardRequest) (*Board, error) {
	var (
		err error
		get *ent.Board
	)
	var id uuid.UUID
	if err := (&id).UnmarshalBinary(req.GetId()); err != nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid argument: %s", err)
	}
	switch req.GetView() {
	case GetBoardRequest_VIEW_UNSPECIFIED, GetBoardRequest_BASIC:
		get, err = svc.client.Board.Get(ctx, id)
	case GetBoardRequest_WITH_EDGE_IDS:
		get, err = svc.client.Board.Query().
			Where(board.ID(id)).
			Only(ctx)
	default:
		return nil, status.Error(codes.InvalidArgument, "invalid argument: unknown view")
	}
	switch {
	case err == nil:
		return toProtoBoard(get)
	case ent.IsNotFound(err):
		return nil, status.Errorf(codes.NotFound, "not found: %s", err)
	default:
		return nil, status.Errorf(codes.Internal, "internal error: %s", err)
	}

}

// Update implements BoardServiceServer.Update
func (svc *BoardService) Update(ctx context.Context, req *UpdateBoardRequest) (*Board, error) {
	board := req.GetBoard()
	var boardID uuid.UUID
	if err := (&boardID).UnmarshalBinary(board.GetId()); err != nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid argument: %s", err)
	}
	m := svc.client.Board.UpdateOneID(boardID)
	boardDescription := board.GetDescription()
	m.SetDescription(boardDescription)
	boardMobileTitle := board.GetMobileTitle()
	m.SetMobileTitle(boardMobileTitle)
	if board.GetNotices() != nil {
		boardNotices := board.GetNotices()
		m.SetNotices(boardNotices)
	}
	boardOrder := uint32(board.GetOrder())
	m.SetOrder(boardOrder)
	boardSearch := board.GetSearch()
	m.SetSearch(boardSearch)
	boardTitle := board.GetTitle()
	m.SetTitle(boardTitle)
	boardUpdatedAt := runtime.ExtractTime(board.GetUpdatedAt())
	m.SetUpdatedAt(boardUpdatedAt)

	res, err := m.Save(ctx)
	switch {
	case err == nil:
		proto, err := toProtoBoard(res)
		if err != nil {
			return nil, status.Errorf(codes.Internal, "internal error: %s", err)
		}
		return proto, nil
	case sqlgraph.IsUniqueConstraintError(err):
		return nil, status.Errorf(codes.AlreadyExists, "already exists: %s", err)
	case ent.IsConstraintError(err):
		return nil, status.Errorf(codes.InvalidArgument, "invalid argument: %s", err)
	default:
		return nil, status.Errorf(codes.Internal, "internal error: %s", err)
	}

}

// Delete implements BoardServiceServer.Delete
func (svc *BoardService) Delete(ctx context.Context, req *DeleteBoardRequest) (*emptypb.Empty, error) {
	var err error
	var id uuid.UUID
	if err := (&id).UnmarshalBinary(req.GetId()); err != nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid argument: %s", err)
	}
	err = svc.client.Board.DeleteOneID(id).Exec(ctx)
	switch {
	case err == nil:
		return &emptypb.Empty{}, nil
	case ent.IsNotFound(err):
		return nil, status.Errorf(codes.NotFound, "not found: %s", err)
	default:
		return nil, status.Errorf(codes.Internal, "internal error: %s", err)
	}

}

// List implements BoardServiceServer.List
func (svc *BoardService) List(ctx context.Context, req *ListBoardRequest) (*ListBoardResponse, error) {
	var (
		err      error
		entList  []*ent.Board
		pageSize int
	)
	pageSize = int(req.GetPageSize())
	switch {
	case pageSize < 0:
		return nil, status.Errorf(codes.InvalidArgument, "page size cannot be less than zero")
	case pageSize == 0 || pageSize > entproto.MaxPageSize:
		pageSize = entproto.MaxPageSize
	}
	listQuery := svc.client.Board.Query().
		Order(ent.Desc(board.FieldID)).
		Limit(pageSize + 1)
	if req.GetPageToken() != "" {
		bytes, err := base64.StdEncoding.DecodeString(req.PageToken)
		if err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "page token is invalid")
		}
		pageToken, err := uuid.ParseBytes(bytes)
		if err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "page token is invalid")
		}
		listQuery = listQuery.
			Where(board.IDLTE(pageToken))
	}
	switch req.GetView() {
	case ListBoardRequest_VIEW_UNSPECIFIED, ListBoardRequest_BASIC:
		entList, err = listQuery.All(ctx)
	case ListBoardRequest_WITH_EDGE_IDS:
		entList, err = listQuery.
			All(ctx)
	}
	switch {
	case err == nil:
		var nextPageToken string
		if len(entList) == pageSize+1 {
			nextPageToken = base64.StdEncoding.EncodeToString(
				[]byte(fmt.Sprintf("%v", entList[len(entList)-1].ID)))
			entList = entList[:len(entList)-1]
		}
		protoList, err := toProtoBoardList(entList)
		if err != nil {
			return nil, status.Errorf(codes.Internal, "internal error: %s", err)
		}
		return &ListBoardResponse{
			BoardList:     protoList,
			NextPageToken: nextPageToken,
		}, nil
	default:
		return nil, status.Errorf(codes.Internal, "internal error: %s", err)
	}

}

// BatchCreate implements BoardServiceServer.BatchCreate
func (svc *BoardService) BatchCreate(ctx context.Context, req *BatchCreateBoardsRequest) (*BatchCreateBoardsResponse, error) {
	requests := req.GetRequests()
	if len(requests) > entproto.MaxBatchCreateSize {
		return nil, status.Errorf(codes.InvalidArgument, "batch size cannot be greater than %d", entproto.MaxBatchCreateSize)
	}
	bulk := make([]*ent.BoardCreate, len(requests))
	for i, req := range requests {
		board := req.GetBoard()
		var err error
		bulk[i], err = svc.createBuilder(board)
		if err != nil {
			return nil, err
		}
	}
	res, err := svc.client.Board.CreateBulk(bulk...).Save(ctx)
	switch {
	case err == nil:
		protoList, err := toProtoBoardList(res)
		if err != nil {
			return nil, status.Errorf(codes.Internal, "internal error: %s", err)
		}
		return &BatchCreateBoardsResponse{
			Boards: protoList,
		}, nil
	case sqlgraph.IsUniqueConstraintError(err):
		return nil, status.Errorf(codes.AlreadyExists, "already exists: %s", err)
	case ent.IsConstraintError(err):
		return nil, status.Errorf(codes.InvalidArgument, "invalid argument: %s", err)
	default:
		return nil, status.Errorf(codes.Internal, "internal error: %s", err)
	}

}

func (svc *BoardService) createBuilder(board *Board) (*ent.BoardCreate, error) {
	m := svc.client.Board.Create()
	boardCreatedAt := runtime.ExtractTime(board.GetCreatedAt())
	m.SetCreatedAt(boardCreatedAt)
	boardDescription := board.GetDescription()
	m.SetDescription(boardDescription)
	boardMobileTitle := board.GetMobileTitle()
	m.SetMobileTitle(boardMobileTitle)
	if board.GetNotices() != nil {
		boardNotices := board.GetNotices()
		m.SetNotices(boardNotices)
	}
	boardOrder := uint32(board.GetOrder())
	m.SetOrder(boardOrder)
	boardSearch := board.GetSearch()
	m.SetSearch(boardSearch)
	boardTitle := board.GetTitle()
	m.SetTitle(boardTitle)
	boardUpdatedAt := runtime.ExtractTime(board.GetUpdatedAt())
	m.SetUpdatedAt(boardUpdatedAt)
	return m, nil
}
