database:
  dialect: sqlite3 # sqlite3, postgres, mysql
  host: 0.0.0.0
  port: 5432
  username: postgres
  password: password
  database: "file::memory:?cache=shared&_fk=1"
  max_open_conns: 10
  max_idle_conns: 5
  conn_max_lifetime: 1h
  logging: true

email:
  username: yourGmailUsername
  password: yourGmailAppPassword
  email_server: smtp.gmail.com
  port: 587
  from: from@gmail.com

services:
  board:
    endpoint: localhost:8081
    version: v1.0.0
  content:
    endpoint: localhost:8082
    version: v1.0.0
  post:
    endpoint: localhost:8083
    version: v1.0.0
  comment:
    endpoint: localhost:8084
    version: v1.0.0
  account:
    endpoint: localhost:8085
    version: v1.0.0
  emailer:
    endpoint: localhost:8086
    version: v1.0.0
  search:
    endpoint: localhost:8087
    version: v1.0.0

features:
  metrics:
    address: prometheus:8125
    enabled: false
  tls:
    cert_file: config/certs/upstream-localhost-cert.pem
    key_file: config/certs/upstream-localhost-key.pem
    ca_file: config/certs/upstream-ca-cert.pem
    servername: "localhost"
    enabled: false
