apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: secrets
  app.kubernetes.io/instance: secrets-abcxzy
  app.kubernetes.io/component: infra

secretGenerator:
#  - name: registry-credentials
#    files:
#      - ".dockerconfigjson=docker.secret.json"
#    type: kubernetes.io/dockerconfigjson
#  - name: certs
#    files:
#      - ca-cert.pem
#      - proxy-cert.pem
#      - proxy-key.pem
#    type: Opaque
