// Code generated by ent, DO NOT EDIT.

package board

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/ygpark2/njro/service/board/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Board {
	return predicate.Board(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Board {
	return predicate.Board(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Board {
	return predicate.Board(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Board {
	return predicate.Board(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Board {
	return predicate.Board(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Board {
	return predicate.Board(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Board {
	return predicate.Board(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Board {
	return predicate.Board(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Board {
	return predicate.Board(sql.FieldLTE(FieldID, id))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Board {
	return predicate.Board(sql.FieldEQ(FieldTitle, v))
}

// MobileTitle applies equality check predicate on the "mobile_title" field. It's identical to MobileTitleEQ.
func MobileTitle(v string) predicate.Board {
	return predicate.Board(sql.FieldEQ(FieldMobileTitle, v))
}

// Order applies equality check predicate on the "order" field. It's identical to OrderEQ.
func Order(v uint32) predicate.Board {
	return predicate.Board(sql.FieldEQ(FieldOrder, v))
}

// Search applies equality check predicate on the "search" field. It's identical to SearchEQ.
func Search(v bool) predicate.Board {
	return predicate.Board(sql.FieldEQ(FieldSearch, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Board {
	return predicate.Board(sql.FieldEQ(FieldDescription, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Board {
	return predicate.Board(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Board {
	return predicate.Board(sql.FieldEQ(FieldUpdatedAt, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Board {
	return predicate.Board(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Board {
	return predicate.Board(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Board {
	return predicate.Board(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Board {
	return predicate.Board(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Board {
	return predicate.Board(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Board {
	return predicate.Board(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Board {
	return predicate.Board(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Board {
	return predicate.Board(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Board {
	return predicate.Board(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Board {
	return predicate.Board(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Board {
	return predicate.Board(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Board {
	return predicate.Board(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Board {
	return predicate.Board(sql.FieldContainsFold(FieldTitle, v))
}

// MobileTitleEQ applies the EQ predicate on the "mobile_title" field.
func MobileTitleEQ(v string) predicate.Board {
	return predicate.Board(sql.FieldEQ(FieldMobileTitle, v))
}

// MobileTitleNEQ applies the NEQ predicate on the "mobile_title" field.
func MobileTitleNEQ(v string) predicate.Board {
	return predicate.Board(sql.FieldNEQ(FieldMobileTitle, v))
}

// MobileTitleIn applies the In predicate on the "mobile_title" field.
func MobileTitleIn(vs ...string) predicate.Board {
	return predicate.Board(sql.FieldIn(FieldMobileTitle, vs...))
}

// MobileTitleNotIn applies the NotIn predicate on the "mobile_title" field.
func MobileTitleNotIn(vs ...string) predicate.Board {
	return predicate.Board(sql.FieldNotIn(FieldMobileTitle, vs...))
}

// MobileTitleGT applies the GT predicate on the "mobile_title" field.
func MobileTitleGT(v string) predicate.Board {
	return predicate.Board(sql.FieldGT(FieldMobileTitle, v))
}

// MobileTitleGTE applies the GTE predicate on the "mobile_title" field.
func MobileTitleGTE(v string) predicate.Board {
	return predicate.Board(sql.FieldGTE(FieldMobileTitle, v))
}

// MobileTitleLT applies the LT predicate on the "mobile_title" field.
func MobileTitleLT(v string) predicate.Board {
	return predicate.Board(sql.FieldLT(FieldMobileTitle, v))
}

// MobileTitleLTE applies the LTE predicate on the "mobile_title" field.
func MobileTitleLTE(v string) predicate.Board {
	return predicate.Board(sql.FieldLTE(FieldMobileTitle, v))
}

// MobileTitleContains applies the Contains predicate on the "mobile_title" field.
func MobileTitleContains(v string) predicate.Board {
	return predicate.Board(sql.FieldContains(FieldMobileTitle, v))
}

// MobileTitleHasPrefix applies the HasPrefix predicate on the "mobile_title" field.
func MobileTitleHasPrefix(v string) predicate.Board {
	return predicate.Board(sql.FieldHasPrefix(FieldMobileTitle, v))
}

// MobileTitleHasSuffix applies the HasSuffix predicate on the "mobile_title" field.
func MobileTitleHasSuffix(v string) predicate.Board {
	return predicate.Board(sql.FieldHasSuffix(FieldMobileTitle, v))
}

// MobileTitleEqualFold applies the EqualFold predicate on the "mobile_title" field.
func MobileTitleEqualFold(v string) predicate.Board {
	return predicate.Board(sql.FieldEqualFold(FieldMobileTitle, v))
}

// MobileTitleContainsFold applies the ContainsFold predicate on the "mobile_title" field.
func MobileTitleContainsFold(v string) predicate.Board {
	return predicate.Board(sql.FieldContainsFold(FieldMobileTitle, v))
}

// OrderEQ applies the EQ predicate on the "order" field.
func OrderEQ(v uint32) predicate.Board {
	return predicate.Board(sql.FieldEQ(FieldOrder, v))
}

// OrderNEQ applies the NEQ predicate on the "order" field.
func OrderNEQ(v uint32) predicate.Board {
	return predicate.Board(sql.FieldNEQ(FieldOrder, v))
}

// OrderIn applies the In predicate on the "order" field.
func OrderIn(vs ...uint32) predicate.Board {
	return predicate.Board(sql.FieldIn(FieldOrder, vs...))
}

// OrderNotIn applies the NotIn predicate on the "order" field.
func OrderNotIn(vs ...uint32) predicate.Board {
	return predicate.Board(sql.FieldNotIn(FieldOrder, vs...))
}

// OrderGT applies the GT predicate on the "order" field.
func OrderGT(v uint32) predicate.Board {
	return predicate.Board(sql.FieldGT(FieldOrder, v))
}

// OrderGTE applies the GTE predicate on the "order" field.
func OrderGTE(v uint32) predicate.Board {
	return predicate.Board(sql.FieldGTE(FieldOrder, v))
}

// OrderLT applies the LT predicate on the "order" field.
func OrderLT(v uint32) predicate.Board {
	return predicate.Board(sql.FieldLT(FieldOrder, v))
}

// OrderLTE applies the LTE predicate on the "order" field.
func OrderLTE(v uint32) predicate.Board {
	return predicate.Board(sql.FieldLTE(FieldOrder, v))
}

// SearchEQ applies the EQ predicate on the "search" field.
func SearchEQ(v bool) predicate.Board {
	return predicate.Board(sql.FieldEQ(FieldSearch, v))
}

// SearchNEQ applies the NEQ predicate on the "search" field.
func SearchNEQ(v bool) predicate.Board {
	return predicate.Board(sql.FieldNEQ(FieldSearch, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Board {
	return predicate.Board(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Board {
	return predicate.Board(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Board {
	return predicate.Board(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Board {
	return predicate.Board(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Board {
	return predicate.Board(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Board {
	return predicate.Board(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Board {
	return predicate.Board(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Board {
	return predicate.Board(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Board {
	return predicate.Board(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Board {
	return predicate.Board(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Board {
	return predicate.Board(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Board {
	return predicate.Board(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Board {
	return predicate.Board(sql.FieldContainsFold(FieldDescription, v))
}

// NoticesIsNil applies the IsNil predicate on the "notices" field.
func NoticesIsNil() predicate.Board {
	return predicate.Board(sql.FieldIsNull(FieldNotices))
}

// NoticesNotNil applies the NotNil predicate on the "notices" field.
func NoticesNotNil() predicate.Board {
	return predicate.Board(sql.FieldNotNull(FieldNotices))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Board {
	return predicate.Board(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Board {
	return predicate.Board(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Board {
	return predicate.Board(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Board {
	return predicate.Board(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Board {
	return predicate.Board(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Board {
	return predicate.Board(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Board {
	return predicate.Board(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Board {
	return predicate.Board(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Board {
	return predicate.Board(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Board {
	return predicate.Board(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Board {
	return predicate.Board(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Board {
	return predicate.Board(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Board {
	return predicate.Board(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Board {
	return predicate.Board(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Board {
	return predicate.Board(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Board {
	return predicate.Board(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Board) predicate.Board {
	return predicate.Board(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Board) predicate.Board {
	return predicate.Board(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Board) predicate.Board {
	return predicate.Board(sql.NotPredicates(p))
}
