// Code generated by ent, DO NOT EDIT.

package content

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/ygpark2/njro/service/content/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Content {
	return predicate.Content(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Content {
	return predicate.Content(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Content {
	return predicate.Content(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Content {
	return predicate.Content(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Content {
	return predicate.Content(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Content {
	return predicate.Content(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Content {
	return predicate.Content(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Content {
	return predicate.Content(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Content {
	return predicate.Content(sql.FieldLTE(FieldID, id))
}

// BoardID applies equality check predicate on the "board_id" field. It's identical to BoardIDEQ.
func BoardID(v string) predicate.Content {
	return predicate.Content(sql.FieldEQ(FieldBoardID, v))
}

// PostID applies equality check predicate on the "post_id" field. It's identical to PostIDEQ.
func PostID(v string) predicate.Content {
	return predicate.Content(sql.FieldEQ(FieldPostID, v))
}

// CommentID applies equality check predicate on the "comment_id" field. It's identical to CommentIDEQ.
func CommentID(v string) predicate.Content {
	return predicate.Content(sql.FieldEQ(FieldCommentID, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.Content {
	return predicate.Content(sql.FieldEQ(FieldContent, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Content {
	return predicate.Content(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Content {
	return predicate.Content(sql.FieldEQ(FieldUpdatedAt, v))
}

// BoardIDEQ applies the EQ predicate on the "board_id" field.
func BoardIDEQ(v string) predicate.Content {
	return predicate.Content(sql.FieldEQ(FieldBoardID, v))
}

// BoardIDNEQ applies the NEQ predicate on the "board_id" field.
func BoardIDNEQ(v string) predicate.Content {
	return predicate.Content(sql.FieldNEQ(FieldBoardID, v))
}

// BoardIDIn applies the In predicate on the "board_id" field.
func BoardIDIn(vs ...string) predicate.Content {
	return predicate.Content(sql.FieldIn(FieldBoardID, vs...))
}

// BoardIDNotIn applies the NotIn predicate on the "board_id" field.
func BoardIDNotIn(vs ...string) predicate.Content {
	return predicate.Content(sql.FieldNotIn(FieldBoardID, vs...))
}

// BoardIDGT applies the GT predicate on the "board_id" field.
func BoardIDGT(v string) predicate.Content {
	return predicate.Content(sql.FieldGT(FieldBoardID, v))
}

// BoardIDGTE applies the GTE predicate on the "board_id" field.
func BoardIDGTE(v string) predicate.Content {
	return predicate.Content(sql.FieldGTE(FieldBoardID, v))
}

// BoardIDLT applies the LT predicate on the "board_id" field.
func BoardIDLT(v string) predicate.Content {
	return predicate.Content(sql.FieldLT(FieldBoardID, v))
}

// BoardIDLTE applies the LTE predicate on the "board_id" field.
func BoardIDLTE(v string) predicate.Content {
	return predicate.Content(sql.FieldLTE(FieldBoardID, v))
}

// BoardIDContains applies the Contains predicate on the "board_id" field.
func BoardIDContains(v string) predicate.Content {
	return predicate.Content(sql.FieldContains(FieldBoardID, v))
}

// BoardIDHasPrefix applies the HasPrefix predicate on the "board_id" field.
func BoardIDHasPrefix(v string) predicate.Content {
	return predicate.Content(sql.FieldHasPrefix(FieldBoardID, v))
}

// BoardIDHasSuffix applies the HasSuffix predicate on the "board_id" field.
func BoardIDHasSuffix(v string) predicate.Content {
	return predicate.Content(sql.FieldHasSuffix(FieldBoardID, v))
}

// BoardIDEqualFold applies the EqualFold predicate on the "board_id" field.
func BoardIDEqualFold(v string) predicate.Content {
	return predicate.Content(sql.FieldEqualFold(FieldBoardID, v))
}

// BoardIDContainsFold applies the ContainsFold predicate on the "board_id" field.
func BoardIDContainsFold(v string) predicate.Content {
	return predicate.Content(sql.FieldContainsFold(FieldBoardID, v))
}

// PostIDEQ applies the EQ predicate on the "post_id" field.
func PostIDEQ(v string) predicate.Content {
	return predicate.Content(sql.FieldEQ(FieldPostID, v))
}

// PostIDNEQ applies the NEQ predicate on the "post_id" field.
func PostIDNEQ(v string) predicate.Content {
	return predicate.Content(sql.FieldNEQ(FieldPostID, v))
}

// PostIDIn applies the In predicate on the "post_id" field.
func PostIDIn(vs ...string) predicate.Content {
	return predicate.Content(sql.FieldIn(FieldPostID, vs...))
}

// PostIDNotIn applies the NotIn predicate on the "post_id" field.
func PostIDNotIn(vs ...string) predicate.Content {
	return predicate.Content(sql.FieldNotIn(FieldPostID, vs...))
}

// PostIDGT applies the GT predicate on the "post_id" field.
func PostIDGT(v string) predicate.Content {
	return predicate.Content(sql.FieldGT(FieldPostID, v))
}

// PostIDGTE applies the GTE predicate on the "post_id" field.
func PostIDGTE(v string) predicate.Content {
	return predicate.Content(sql.FieldGTE(FieldPostID, v))
}

// PostIDLT applies the LT predicate on the "post_id" field.
func PostIDLT(v string) predicate.Content {
	return predicate.Content(sql.FieldLT(FieldPostID, v))
}

// PostIDLTE applies the LTE predicate on the "post_id" field.
func PostIDLTE(v string) predicate.Content {
	return predicate.Content(sql.FieldLTE(FieldPostID, v))
}

// PostIDContains applies the Contains predicate on the "post_id" field.
func PostIDContains(v string) predicate.Content {
	return predicate.Content(sql.FieldContains(FieldPostID, v))
}

// PostIDHasPrefix applies the HasPrefix predicate on the "post_id" field.
func PostIDHasPrefix(v string) predicate.Content {
	return predicate.Content(sql.FieldHasPrefix(FieldPostID, v))
}

// PostIDHasSuffix applies the HasSuffix predicate on the "post_id" field.
func PostIDHasSuffix(v string) predicate.Content {
	return predicate.Content(sql.FieldHasSuffix(FieldPostID, v))
}

// PostIDEqualFold applies the EqualFold predicate on the "post_id" field.
func PostIDEqualFold(v string) predicate.Content {
	return predicate.Content(sql.FieldEqualFold(FieldPostID, v))
}

// PostIDContainsFold applies the ContainsFold predicate on the "post_id" field.
func PostIDContainsFold(v string) predicate.Content {
	return predicate.Content(sql.FieldContainsFold(FieldPostID, v))
}

// CommentIDEQ applies the EQ predicate on the "comment_id" field.
func CommentIDEQ(v string) predicate.Content {
	return predicate.Content(sql.FieldEQ(FieldCommentID, v))
}

// CommentIDNEQ applies the NEQ predicate on the "comment_id" field.
func CommentIDNEQ(v string) predicate.Content {
	return predicate.Content(sql.FieldNEQ(FieldCommentID, v))
}

// CommentIDIn applies the In predicate on the "comment_id" field.
func CommentIDIn(vs ...string) predicate.Content {
	return predicate.Content(sql.FieldIn(FieldCommentID, vs...))
}

// CommentIDNotIn applies the NotIn predicate on the "comment_id" field.
func CommentIDNotIn(vs ...string) predicate.Content {
	return predicate.Content(sql.FieldNotIn(FieldCommentID, vs...))
}

// CommentIDGT applies the GT predicate on the "comment_id" field.
func CommentIDGT(v string) predicate.Content {
	return predicate.Content(sql.FieldGT(FieldCommentID, v))
}

// CommentIDGTE applies the GTE predicate on the "comment_id" field.
func CommentIDGTE(v string) predicate.Content {
	return predicate.Content(sql.FieldGTE(FieldCommentID, v))
}

// CommentIDLT applies the LT predicate on the "comment_id" field.
func CommentIDLT(v string) predicate.Content {
	return predicate.Content(sql.FieldLT(FieldCommentID, v))
}

// CommentIDLTE applies the LTE predicate on the "comment_id" field.
func CommentIDLTE(v string) predicate.Content {
	return predicate.Content(sql.FieldLTE(FieldCommentID, v))
}

// CommentIDContains applies the Contains predicate on the "comment_id" field.
func CommentIDContains(v string) predicate.Content {
	return predicate.Content(sql.FieldContains(FieldCommentID, v))
}

// CommentIDHasPrefix applies the HasPrefix predicate on the "comment_id" field.
func CommentIDHasPrefix(v string) predicate.Content {
	return predicate.Content(sql.FieldHasPrefix(FieldCommentID, v))
}

// CommentIDHasSuffix applies the HasSuffix predicate on the "comment_id" field.
func CommentIDHasSuffix(v string) predicate.Content {
	return predicate.Content(sql.FieldHasSuffix(FieldCommentID, v))
}

// CommentIDEqualFold applies the EqualFold predicate on the "comment_id" field.
func CommentIDEqualFold(v string) predicate.Content {
	return predicate.Content(sql.FieldEqualFold(FieldCommentID, v))
}

// CommentIDContainsFold applies the ContainsFold predicate on the "comment_id" field.
func CommentIDContainsFold(v string) predicate.Content {
	return predicate.Content(sql.FieldContainsFold(FieldCommentID, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.Content {
	return predicate.Content(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.Content {
	return predicate.Content(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.Content {
	return predicate.Content(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.Content {
	return predicate.Content(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.Content {
	return predicate.Content(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.Content {
	return predicate.Content(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.Content {
	return predicate.Content(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.Content {
	return predicate.Content(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.Content {
	return predicate.Content(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.Content {
	return predicate.Content(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.Content {
	return predicate.Content(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.Content {
	return predicate.Content(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.Content {
	return predicate.Content(sql.FieldContainsFold(FieldContent, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Content {
	return predicate.Content(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Content {
	return predicate.Content(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Content {
	return predicate.Content(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Content {
	return predicate.Content(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Content {
	return predicate.Content(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Content {
	return predicate.Content(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Content {
	return predicate.Content(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Content {
	return predicate.Content(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Content {
	return predicate.Content(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Content {
	return predicate.Content(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Content {
	return predicate.Content(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Content {
	return predicate.Content(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Content {
	return predicate.Content(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Content {
	return predicate.Content(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Content {
	return predicate.Content(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Content {
	return predicate.Content(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Content) predicate.Content {
	return predicate.Content(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Content) predicate.Content {
	return predicate.Content(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Content) predicate.Content {
	return predicate.Content(sql.NotPredicates(p))
}
