// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/ygpark2/njro/service/board/ent/board"
	"github.com/ygpark2/njro/service/board/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	boardFields := schema.Board{}.Fields()
	_ = boardFields
	// boardDescTitle is the schema descriptor for title field.
	boardDescTitle := boardFields[1].Descriptor()
	// board.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	board.TitleValidator = boardDescTitle.Validators[0].(func(string) error)
	// boardDescMobileTitle is the schema descriptor for mobile_title field.
	boardDescMobileTitle := boardFields[2].Descriptor()
	// board.MobileTitleValidator is a validator for the "mobile_title" field. It is called by the builders before save.
	board.MobileTitleValidator = boardDescMobileTitle.Validators[0].(func(string) error)
	// boardDescOrder is the schema descriptor for order field.
	boardDescOrder := boardFields[3].Descriptor()
	// board.DefaultOrder holds the default value on creation for the order field.
	board.DefaultOrder = boardDescOrder.Default.(uint32)
	// boardDescSearch is the schema descriptor for search field.
	boardDescSearch := boardFields[4].Descriptor()
	// board.DefaultSearch holds the default value on creation for the search field.
	board.DefaultSearch = boardDescSearch.Default.(bool)
	// boardDescDescription is the schema descriptor for description field.
	boardDescDescription := boardFields[5].Descriptor()
	// board.DefaultDescription holds the default value on creation for the description field.
	board.DefaultDescription = boardDescDescription.Default.(string)
	// boardDescCreatedAt is the schema descriptor for created_at field.
	boardDescCreatedAt := boardFields[7].Descriptor()
	// board.DefaultCreatedAt holds the default value on creation for the created_at field.
	board.DefaultCreatedAt = boardDescCreatedAt.Default.(func() time.Time)
	// boardDescUpdatedAt is the schema descriptor for updated_at field.
	boardDescUpdatedAt := boardFields[8].Descriptor()
	// board.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	board.DefaultUpdatedAt = boardDescUpdatedAt.Default.(func() time.Time)
	// board.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	board.UpdateDefaultUpdatedAt = boardDescUpdatedAt.UpdateDefault.(func() time.Time)
	// boardDescID is the schema descriptor for id field.
	boardDescID := boardFields[0].Descriptor()
	// board.DefaultID holds the default value on creation for the id field.
	board.DefaultID = boardDescID.Default.(func() uuid.UUID)
}
