// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CommentsColumns holds the columns for the "comments" table.
	CommentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "board_id", Type: field.TypeString},
		{Name: "post_id", Type: field.TypeString},
		{Name: "content_id", Type: field.TypeString, Default: ""},
		{Name: "userid", Type: field.TypeString},
		{Name: "username", Type: field.TypeString, Default: ""},
		{Name: "nickname", Type: field.TypeString, Default: ""},
		{Name: "email", Type: field.TypeString, Default: ""},
		{Name: "password", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "content", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "url", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "use_html", Type: field.TypeBool, Default: false},
		{Name: "use_secret", Type: field.TypeBool, Default: false},
		{Name: "up_vote_count", Type: field.TypeUint32, Default: 0},
		{Name: "down_vote_count", Type: field.TypeUint32, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// CommentsTable holds the schema information for the "comments" table.
	CommentsTable = &schema.Table{
		Name:       "comments",
		Columns:    CommentsColumns,
		PrimaryKey: []*schema.Column{CommentsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CommentsTable,
	}
)

func init() {
}
