// Code generated by protoc-gen-entgrpc. DO NOT EDIT.
package entpb

import (
	context "context"
	base64 "encoding/base64"
	entproto "entgo.io/contrib/entproto"
	runtime "entgo.io/contrib/entproto/runtime"
	sqlgraph "entgo.io/ent/dialect/sql/sqlgraph"
	fmt "fmt"
	uuid "github.com/google/uuid"
	ent "github.com/ygpark2/njro/service/content/ent"
	content "github.com/ygpark2/njro/service/content/ent/content"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

// ContentService implements ContentServiceServer
type ContentService struct {
	client *ent.Client
	UnimplementedContentServiceServer
}

// NewContentService returns a new ContentService
func NewContentService(client *ent.Client) *ContentService {
	return &ContentService{
		client: client,
	}
}

// toProtoContent transforms the ent type to the pb type
func toProtoContent(e *ent.Content) (*Content, error) {
	v := &Content{}
	board_id := e.BoardID
	v.BoardId = board_id
	comment_id := e.CommentID
	v.CommentId = comment_id
	content := e.Content
	v.Content = content
	created_at := timestamppb.New(e.CreatedAt)
	v.CreatedAt = created_at
	id, err := e.ID.MarshalBinary()
	if err != nil {
		return nil, err
	}
	v.Id = id
	post_id := e.PostID
	v.PostId = post_id
	updated_at := timestamppb.New(e.UpdatedAt)
	v.UpdatedAt = updated_at
	return v, nil
}

// toProtoContentList transforms a list of ent type to a list of pb type
func toProtoContentList(e []*ent.Content) ([]*Content, error) {
	var pbList []*Content
	for _, entEntity := range e {
		pbEntity, err := toProtoContent(entEntity)
		if err != nil {
			return nil, status.Errorf(codes.Internal, "internal error: %s", err)
		}
		pbList = append(pbList, pbEntity)
	}
	return pbList, nil
}

// Create implements ContentServiceServer.Create
func (svc *ContentService) Create(ctx context.Context, req *CreateContentRequest) (*Content, error) {
	content := req.GetContent()
	m, err := svc.createBuilder(content)
	if err != nil {
		return nil, err
	}
	res, err := m.Save(ctx)
	switch {
	case err == nil:
		proto, err := toProtoContent(res)
		if err != nil {
			return nil, status.Errorf(codes.Internal, "internal error: %s", err)
		}
		return proto, nil
	case sqlgraph.IsUniqueConstraintError(err):
		return nil, status.Errorf(codes.AlreadyExists, "already exists: %s", err)
	case ent.IsConstraintError(err):
		return nil, status.Errorf(codes.InvalidArgument, "invalid argument: %s", err)
	default:
		return nil, status.Errorf(codes.Internal, "internal error: %s", err)
	}

}

// Get implements ContentServiceServer.Get
func (svc *ContentService) Get(ctx context.Context, req *GetContentRequest) (*Content, error) {
	var (
		err error
		get *ent.Content
	)
	var id uuid.UUID
	if err := (&id).UnmarshalBinary(req.GetId()); err != nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid argument: %s", err)
	}
	switch req.GetView() {
	case GetContentRequest_VIEW_UNSPECIFIED, GetContentRequest_BASIC:
		get, err = svc.client.Content.Get(ctx, id)
	case GetContentRequest_WITH_EDGE_IDS:
		get, err = svc.client.Content.Query().
			Where(content.ID(id)).
			Only(ctx)
	default:
		return nil, status.Error(codes.InvalidArgument, "invalid argument: unknown view")
	}
	switch {
	case err == nil:
		return toProtoContent(get)
	case ent.IsNotFound(err):
		return nil, status.Errorf(codes.NotFound, "not found: %s", err)
	default:
		return nil, status.Errorf(codes.Internal, "internal error: %s", err)
	}

}

// Update implements ContentServiceServer.Update
func (svc *ContentService) Update(ctx context.Context, req *UpdateContentRequest) (*Content, error) {
	content := req.GetContent()
	var contentID uuid.UUID
	if err := (&contentID).UnmarshalBinary(content.GetId()); err != nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid argument: %s", err)
	}
	m := svc.client.Content.UpdateOneID(contentID)
	contentCommentID := content.GetCommentId()
	m.SetCommentID(contentCommentID)
	contentContent := content.GetContent()
	m.SetContent(contentContent)
	contentUpdatedAt := runtime.ExtractTime(content.GetUpdatedAt())
	m.SetUpdatedAt(contentUpdatedAt)

	res, err := m.Save(ctx)
	switch {
	case err == nil:
		proto, err := toProtoContent(res)
		if err != nil {
			return nil, status.Errorf(codes.Internal, "internal error: %s", err)
		}
		return proto, nil
	case sqlgraph.IsUniqueConstraintError(err):
		return nil, status.Errorf(codes.AlreadyExists, "already exists: %s", err)
	case ent.IsConstraintError(err):
		return nil, status.Errorf(codes.InvalidArgument, "invalid argument: %s", err)
	default:
		return nil, status.Errorf(codes.Internal, "internal error: %s", err)
	}

}

// Delete implements ContentServiceServer.Delete
func (svc *ContentService) Delete(ctx context.Context, req *DeleteContentRequest) (*emptypb.Empty, error) {
	var err error
	var id uuid.UUID
	if err := (&id).UnmarshalBinary(req.GetId()); err != nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid argument: %s", err)
	}
	err = svc.client.Content.DeleteOneID(id).Exec(ctx)
	switch {
	case err == nil:
		return &emptypb.Empty{}, nil
	case ent.IsNotFound(err):
		return nil, status.Errorf(codes.NotFound, "not found: %s", err)
	default:
		return nil, status.Errorf(codes.Internal, "internal error: %s", err)
	}

}

// List implements ContentServiceServer.List
func (svc *ContentService) List(ctx context.Context, req *ListContentRequest) (*ListContentResponse, error) {
	var (
		err      error
		entList  []*ent.Content
		pageSize int
	)
	pageSize = int(req.GetPageSize())
	switch {
	case pageSize < 0:
		return nil, status.Errorf(codes.InvalidArgument, "page size cannot be less than zero")
	case pageSize == 0 || pageSize > entproto.MaxPageSize:
		pageSize = entproto.MaxPageSize
	}
	listQuery := svc.client.Content.Query().
		Order(ent.Desc(content.FieldID)).
		Limit(pageSize + 1)
	if req.GetPageToken() != "" {
		bytes, err := base64.StdEncoding.DecodeString(req.PageToken)
		if err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "page token is invalid")
		}
		pageToken, err := uuid.ParseBytes(bytes)
		if err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "page token is invalid")
		}
		listQuery = listQuery.
			Where(content.IDLTE(pageToken))
	}
	switch req.GetView() {
	case ListContentRequest_VIEW_UNSPECIFIED, ListContentRequest_BASIC:
		entList, err = listQuery.All(ctx)
	case ListContentRequest_WITH_EDGE_IDS:
		entList, err = listQuery.
			All(ctx)
	}
	switch {
	case err == nil:
		var nextPageToken string
		if len(entList) == pageSize+1 {
			nextPageToken = base64.StdEncoding.EncodeToString(
				[]byte(fmt.Sprintf("%v", entList[len(entList)-1].ID)))
			entList = entList[:len(entList)-1]
		}
		protoList, err := toProtoContentList(entList)
		if err != nil {
			return nil, status.Errorf(codes.Internal, "internal error: %s", err)
		}
		return &ListContentResponse{
			ContentList:   protoList,
			NextPageToken: nextPageToken,
		}, nil
	default:
		return nil, status.Errorf(codes.Internal, "internal error: %s", err)
	}

}

// BatchCreate implements ContentServiceServer.BatchCreate
func (svc *ContentService) BatchCreate(ctx context.Context, req *BatchCreateContentsRequest) (*BatchCreateContentsResponse, error) {
	requests := req.GetRequests()
	if len(requests) > entproto.MaxBatchCreateSize {
		return nil, status.Errorf(codes.InvalidArgument, "batch size cannot be greater than %d", entproto.MaxBatchCreateSize)
	}
	bulk := make([]*ent.ContentCreate, len(requests))
	for i, req := range requests {
		content := req.GetContent()
		var err error
		bulk[i], err = svc.createBuilder(content)
		if err != nil {
			return nil, err
		}
	}
	res, err := svc.client.Content.CreateBulk(bulk...).Save(ctx)
	switch {
	case err == nil:
		protoList, err := toProtoContentList(res)
		if err != nil {
			return nil, status.Errorf(codes.Internal, "internal error: %s", err)
		}
		return &BatchCreateContentsResponse{
			Contents: protoList,
		}, nil
	case sqlgraph.IsUniqueConstraintError(err):
		return nil, status.Errorf(codes.AlreadyExists, "already exists: %s", err)
	case ent.IsConstraintError(err):
		return nil, status.Errorf(codes.InvalidArgument, "invalid argument: %s", err)
	default:
		return nil, status.Errorf(codes.Internal, "internal error: %s", err)
	}

}

func (svc *ContentService) createBuilder(content *Content) (*ent.ContentCreate, error) {
	m := svc.client.Content.Create()
	contentBoardID := content.GetBoardId()
	m.SetBoardID(contentBoardID)
	contentCommentID := content.GetCommentId()
	m.SetCommentID(contentCommentID)
	contentContent := content.GetContent()
	m.SetContent(contentContent)
	contentCreatedAt := runtime.ExtractTime(content.GetCreatedAt())
	m.SetCreatedAt(contentCreatedAt)
	contentPostID := content.GetPostId()
	m.SetPostID(contentPostID)
	contentUpdatedAt := runtime.ExtractTime(content.GetUpdatedAt())
	m.SetUpdatedAt(contentUpdatedAt)
	return m, nil
}
